/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/unique/150.glb -o models/gltfjsx/unique/150.jsx 
Author: Cubone0711 (https://sketchfab.com/Cubone0711)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mobile-pokemon-go-150-armored-mewtwo-2ac5dee2754c468a91fc9aa48b7a9883
Title: Mobile - Pokemon GO - 150 Armored Mewtwo
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/unique/150.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_190.geometry} material={materials.Body} skeleton={nodes.Object_190.skeleton} />
      <skinnedMesh geometry={nodes.Object_192.geometry} material={materials.ArmorA} skeleton={nodes.Object_192.skeleton} />
      <skinnedMesh geometry={nodes.Object_194.geometry} material={materials.ArmorB} skeleton={nodes.Object_194.skeleton} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/unique/150.glb')
