/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/unique/658.glb -o models/gltfjsx/unique/658.jsx 
Author: 197emmet (https://sketchfab.com/197emmet)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ash-greninja-3517af1ad21a4bfa9c4b36263fdfa4a1
Title: Ash- Greninja
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 658(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/unique/658.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_81.geometry} material={materials['7_model_0_0_0']} skeleton={nodes.Object_81.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Object_82.geometry} material={materials['6_model.part.003_1_0_0']} skeleton={nodes.Object_82.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Object_83.geometry} material={materials['6_model.part.002_1_0_0']} skeleton={nodes.Object_83.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Object_84.geometry} material={materials['6_model.part.001_1_0_0']} skeleton={nodes.Object_84.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/unique/658.glb')
