/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/unique/890.glb -o models/gltfjsx/unique/890.jsx 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function 890(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/unique/890.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials.PaletteMaterial001} position={[-29.009, 19.125, 13.015]} rotation={[-0.01, -0.052, -0.04]} scale={[0.034, 0.713, 0.765]} />
        <group name="EndPin001" position={[-44.805, 36.809, -6.602]} rotation={[1.239, 0.458, 0.827]} scale={6.184}>
          <mesh name="Cone011" geometry={nodes.Cone011.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cone011_1" geometry={nodes.Cone011_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cone011_2" geometry={nodes.Cone011_2.geometry} material={materials.PaletteMaterial001} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/unique/890.glb')
