/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/mega/384.glb -o models/gltfjsx/mega/384.jsx 
Author: LunaEagle (https://sketchfab.com/LunaEagle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rayquaza-mega-a5cadc90a46d4816902a0ad0ef368568
Title: Rayquaza Mega
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/mega/384.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.pm0384_51_00_BodyB} skeleton={nodes.Object_6.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.pm0384_51_00_BodyAEnv01} skeleton={nodes.Object_7.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.pm0384_51_00_BodyAEnv01} skeleton={nodes.Object_8.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.pm0384_51_00_BodyAEnv01} skeleton={nodes.Object_9.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.pm0384_51_00_BodyAEnv01} skeleton={nodes.Object_10.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.pm0384_51_00_BodyAEnv01} skeleton={nodes.Object_11.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.pm0384_51_00_BodyAEnv01} skeleton={nodes.Object_12.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.pm0384_51_00_BodyAEnv01} skeleton={nodes.Object_13.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.pm0384_51_00_Eye} skeleton={nodes.Object_14.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.pm0384_51_00_BodyAEnv01} skeleton={nodes.Object_15.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.pm0384_51_00_BodyAEnv01} skeleton={nodes.Object_16.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.pm0384_51_00_BodyAEnv01} skeleton={nodes.Object_17.skeleton} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/mega/384.glb')
