/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/1002.glb -o models/gltfjsx/shiny/1002.jsx 
Author: Mariokart07 (https://sketchfab.com/Mariokart07)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiny-chien-pao-d24120cad4204d8994324dead434e3a7
Title: Shiny Chien Pao
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/1002.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.material_2} position={[-0.081, 1.063, 1.138]} rotation={[Math.PI / 2, 0, 0.873]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.material_3} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.material_4} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.material_5} position={[0.125, 0.938, 1.188]} rotation={[Math.PI / 2, 0, -Math.PI / 3]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/1002.glb')
