/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/1008.glb -o models/gltfjsx/shiny/1008.jsx 
Author: Mariokart07 (https://sketchfab.com/Mariokart07)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiny-miraidon-dfc40312c4814b7481c5a4f722e60cdb
Title: Shiny Miraidon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/1008.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.material_2} position={[0, 0.563, 0.5]} rotation={[-Math.PI / 4, 0, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.material_3} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.material_4} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.material_5} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.material_6} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.material_7} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.material_8} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.material_9} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.material_10} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.material_11} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.material_12} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.material_13} position={[0, -0.125, 0.063]} rotation={[Math.PI / 4, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/1008.glb')
