/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/12.glb -o models/gltfjsx/shiny/12.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/12.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <primitive object={nodes.Spine} />
      <group position={[0.036, -0.001, 0]} rotation={[-Math.PI / 2, -0.054, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.ButterfreeF_1.geometry} material={materials['Material #96']} skeleton={nodes.ButterfreeF_1.skeleton} />
        <skinnedMesh geometry={nodes.ButterfreeF_2.geometry} material={materials['Material #97']} skeleton={nodes.ButterfreeF_2.skeleton} />
        <skinnedMesh geometry={nodes.ButterfreeF_3.geometry} material={materials['Material #98']} skeleton={nodes.ButterfreeF_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/12.glb')
