/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/129.glb -o models/gltfjsx/shiny/129.jsx 
Author: paolavalenciamu (https://sketchfab.com/paolavalenciamu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magikarp-shiny-pokemon-4399bbc2ce3747e9ac9d977681304016
Title: Magikarp Shiny Pokemon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/129.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_7.geometry} material={materials.Body} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Eyes} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/129.glb')
