/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/149.glb -o models/gltfjsx/shiny/149.jsx 
Author: Mariokart07 (https://sketchfab.com/Mariokart07)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiny-dragonite-f0ace338ce01473981e30480e455251f
Title: Shiny Dragonite
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 149(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/shiny/149.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_3} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/shiny/149.glb')
