/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/186.glb -o models/gltfjsx/shiny/186.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/186.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_4__BodyBTattu_.geometry} material={materials.BodyBTattu} />
      <mesh geometry={nodes.Mesh_6__BodyATattu01_.geometry} material={materials.BodyATattu01} />
      <mesh geometry={nodes.Mesh_1__Eye_.geometry} material={materials.Eye} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/186.glb')
