/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/25.glb -o models/gltfjsx/shiny/25.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/25.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="GLTF_created_0" position={[-0.009, -1.373, 0.13]} rotation={[Math.PI / 2, 0, 0]} scale={4.525}>
          <primitive object={nodes.GLTF_created_0_rootJoint} />
        </group>
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Mouth} skeleton={nodes.Object_11.skeleton} position={[-0.009, -1.373, 0.13]} rotation={[Math.PI / 2, 0, 0]} scale={4.525} />
        <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.BodyB} skeleton={nodes.Object_13.skeleton} position={[-0.009, -1.373, 0.13]} rotation={[Math.PI / 2, 0, 0]} scale={4.525} />
        <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.face} skeleton={nodes.Object_15.skeleton} position={[-0.009, -1.373, 0.13]} rotation={[Math.PI / 2, 0, 0]} scale={4.525} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.BodyA} skeleton={nodes.Object_7.skeleton} position={[-0.009, -1.373, 0.13]} rotation={[Math.PI / 2, 0, 0]} scale={4.525} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.material} skeleton={nodes.Object_9.skeleton} position={[-0.009, -1.373, 0.13]} rotation={[Math.PI / 2, 0, 0]} scale={4.525} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/25.glb')
