/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/26.glb -o models/gltfjsx/shiny/26.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/26.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <primitive object={nodes.Spine1} />
      <group position={[0, 0.749, 0.028]} rotation={[-Math.PI / 2, -0.007, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.RaichuF_1.geometry} material={materials['Material #146']} skeleton={nodes.RaichuF_1.skeleton} />
        <skinnedMesh geometry={nodes.RaichuF_2.geometry} material={materials['Material #147']} skeleton={nodes.RaichuF_2.skeleton} />
        <skinnedMesh geometry={nodes.RaichuF_3.geometry} material={materials['Material #148']} skeleton={nodes.RaichuF_3.skeleton} />
        <skinnedMesh geometry={nodes.RaichuF_4.geometry} material={materials['Material #149']} skeleton={nodes.RaichuF_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/26.glb')
