/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/31.glb -o models/gltfjsx/shiny/31.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/31.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <primitive object={nodes.Spine1} />
      <group position={[-0.032, -0.162, 0]} rotation={[-Math.PI / 2, -0.016, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Nidoqueen_1.geometry} material={materials['Material #127']} skeleton={nodes.Nidoqueen_1.skeleton} />
        <skinnedMesh geometry={nodes.Nidoqueen_2.geometry} material={materials['Material #128']} skeleton={nodes.Nidoqueen_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/31.glb')
