/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/376.glb -o models/gltfjsx/shiny/376.jsx 
Author: Dylan Spin (https://sketchfab.com/DylanSpin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiny-metagross-c78d91f041bd41e8928830d0290ef2cf
Title: Shiny Metagross
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/376.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Sphere006_0" position={[0.272, 2.972, 0.419]} rotation={[0, 0.483, 0]} scale={0.091}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="Sphere011_1" position={[-0.294, 2.931, 0.391]} rotation={[-0.113, -0.701, -0.174]} scale={0.091}>
            <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="Sphere012_2" position={[-0.294, 2.931, -0.391]} rotation={[-2.982, -0.754, -2.942]} scale={0.091}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="Sphere013_3" position={[0.272, 2.972, -0.419]} rotation={[-2.909, 0.599, Math.PI]} scale={0.091}>
            <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="Boddy_4" position={[0.056, 2.644, 0]} rotation={[0, 0, 0.09]} scale={[0.539, 0.1, 0.539]}>
            <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.PaletteMaterial003} />
            <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.PaletteMaterial002} />
            <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.PaletteMaterial004} />
            <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.PaletteMaterial005} />
          </group>
          <group name="FrontCross_5" position={[-0.641, 2.781, 0]} rotation={[0, 0, -0.535]} scale={[0.126, 0.387, 0.09]}>
            <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.PaletteMaterial002} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/376.glb')
