/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/38.glb -o models/gltfjsx/shiny/38.jsx 
Author: animalSS (https://sketchfab.com/animalSS)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiny-ninetales-20f1b0bb8a9a4a5eb6736c9ec4df9937
Title: Shiny Ninetales
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 38(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/shiny/38.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ninetales_0.geometry} material={materials.material} scale={0.025} />
      <mesh geometry={nodes.Ninetales_1.geometry} material={materials.BodyA00} scale={0.025} />
      <mesh geometry={nodes.Ninetales_2.geometry} material={materials.BodyB} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/shiny/38.glb')
