/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/6.glb -o models/gltfjsx/shiny/6.jsx 
Author: Mariokart07 (https://sketchfab.com/Mariokart07)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiny-charizard-8009060100cc49b39560ba438d97578f
Title: Shiny Charizard
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 6(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/shiny/6.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.material_3} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.material_4} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/shiny/6.glb')
