/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/61.glb -o models/gltfjsx/shiny/61.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/61.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes['004_Hips']} />
      <primitive object={nodes['016_Spine']} />
      <group position={[0.004, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Poliwhirl_1.geometry} material={materials.BodyNyorobon} skeleton={nodes.Poliwhirl_1.skeleton} />
        <skinnedMesh geometry={nodes.Poliwhirl_2.geometry} material={materials.Eye} skeleton={nodes.Poliwhirl_2.skeleton} />
        <skinnedMesh geometry={nodes.Poliwhirl_3.geometry} material={materials.RIris} skeleton={nodes.Poliwhirl_3.skeleton} />
        <skinnedMesh geometry={nodes.Poliwhirl_4.geometry} material={materials.RIris} skeleton={nodes.Poliwhirl_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/61.glb')
