/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/708.glb -o models/gltfjsx/shiny/708.jsx 
Author: Ergoni (https://sketchfab.com/Ergoni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phantump-shiny-c38328f65ad849d2aa2387eeb3b4e4a9
Title: Phantump Shiny
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/708.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Flame_Gradient-emi_0'].geometry} material={materials['Gradient-emi']} position={[569.042, 26.138, -86.077]} rotation={[-1.569, -0.015, 0.132]} scale={29.515} />
      <mesh geometry={nodes.Phantump_low_Phantump_0.geometry} material={materials.Phantump} position={[520.985, 0, 0]} scale={1.002} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/708.glb')
