/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/8.glb -o models/gltfjsx/shiny/8.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/8.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Waist} />
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Wartortle_1.geometry} material={materials['Material #72']} skeleton={nodes.Wartortle_1.skeleton} />
        <skinnedMesh geometry={nodes.Wartortle_2.geometry} material={materials['Material #73']} skeleton={nodes.Wartortle_2.skeleton} />
        <skinnedMesh geometry={nodes.Wartortle_3.geometry} material={materials['Material #74']} skeleton={nodes.Wartortle_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/8.glb')
