/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/803.glb -o models/gltfjsx/shiny/803.jsx 
Author: LunaEagle (https://sketchfab.com/LunaEagle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/poipole-shiny-9de27c2549714df6b1dc857e68695379
Title: Poipole shiny
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/803.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials['pm0886_00_Mouth1_tga_png-material']} skeleton={nodes.Object_6.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials['pm0886_00_Eye1_tga_png-material']} skeleton={nodes.Object_8.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials['pm0886_00_Body1_tga_png-material']} skeleton={nodes.Object_10.skeleton} scale={0.01} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/803.glb')
