/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/809.glb -o models/gltfjsx/shiny/809.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/809.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={1} decay={2} position={[6.48, 24.793, 20.624]} rotation={[0, 1.26, 0]} target={nodes.DirectionalLight.target}>
        <primitive object={nodes.DirectionalLight.target} position={[0, 0, -1]} />
      </directionalLight>
      <directionalLight intensity={1} decay={2} position={[-15.807, 26.409, -7.961]} target={nodes.DirectionalLight_2.target}>
        <primitive object={nodes.DirectionalLight_2.target} position={[0, 0, -1]} />
      </directionalLight>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0.024, 3.345, 0.165]} scale={[1.223, 1, 1.277]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.PaletteMaterial002} position={[-0.089, 5.966, 3.697]} rotation={[Math.PI / 2, -Math.PI / 6, Math.PI]} scale={[2.315, 0.671, 2.315]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.PaletteMaterial003} position={[-1.392, 2.731, 0.199]} rotation={[0, 0, 1.189]} scale={0.085} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/809.glb')
