/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/9.glb -o models/gltfjsx/shiny/9.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/9.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Waist} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Blastoise_1.geometry} material={materials['Material #87']} skeleton={nodes.Blastoise_1.skeleton} />
        <skinnedMesh geometry={nodes.Blastoise_2.geometry} material={materials['Material #86']} skeleton={nodes.Blastoise_2.skeleton} />
        <skinnedMesh geometry={nodes.Blastoise_3.geometry} material={materials['Material #85']} skeleton={nodes.Blastoise_3.skeleton} />
        <skinnedMesh geometry={nodes.Blastoise_4.geometry} material={materials['Material #88']} skeleton={nodes.Blastoise_4.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.Blastoise_CannonsA.geometry} material={materials['Material #86']} skeleton={nodes.Blastoise_CannonsA.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Blastoise_CannonsB.geometry} material={materials['Material #86']} skeleton={nodes.Blastoise_CannonsB.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/shiny/9.glb')
