/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/shiny/984.glb -o models/gltfjsx/shiny/984.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 984(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/shiny/984.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <primitive object={nodes._rootJoint_1} />
        <skinnedMesh name="Object_508" geometry={nodes.Object_508.geometry} material={materials.Shiny_Body_B} skeleton={nodes.Object_508.skeleton} position={[4.558, 0, 0]} />
        <skinnedMesh name="Object_510" geometry={nodes.Object_510.geometry} material={materials.r_eye_Shiny} skeleton={nodes.Object_510.skeleton} position={[4.558, 0, 0]} />
        <skinnedMesh name="Object_511" geometry={nodes.Object_511.geometry} material={materials.r_eye_Shiny} skeleton={nodes.Object_511.skeleton} position={[4.558, 0, 0]} />
        <skinnedMesh name="Object_513" geometry={nodes.Object_513.geometry} material={materials.Shiny_Body} skeleton={nodes.Object_513.skeleton} position={[4.558, 0, 0]} />
        <skinnedMesh name="Object_514" geometry={nodes.Object_514.geometry} material={materials.Shiny_Body_B} skeleton={nodes.Object_514.skeleton} position={[4.558, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/shiny/984.glb')
