/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/origin/487.glb -o models/gltfjsx/origin/487.jsx 
Author: BodeMAN (https://sketchfab.com/dioguinifrsilva)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-giratina-origin-240a861506294310b0e323a10a28fceb
Title: Pokémon Giratina (origin)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 487(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/origin/487.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_Body_0.geometry} material={materials.Body} position={[0, 0.699, -0.057]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_Material002_0.geometry} material={materials['Material.002']} position={[0, 0.699, -0.057]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_Material003_0.geometry} material={materials['Material.003']} position={[0, 0.699, -0.057]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_Material004_0.geometry} material={materials['Material.004']} position={[0, 0.699, -0.057]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_Material023_0.geometry} material={materials['Material.023']} position={[0, 0.699, -0.057]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_Material026_0.geometry} material={materials['Material.026']} position={[0, 0.699, -0.057]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_Material005_0.geometry} material={materials['Material.005']} position={[0, 0.699, -0.057]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_Material006_0.geometry} material={materials['Material.006']} position={[0, 0.699, -0.057]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_Material019_0.geometry} material={materials['Material.019']} position={[0, 0.699, -0.057]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} position={[0, 0.699, -0.057]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/origin/487.glb')
