/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/1.glb -o models/gltfjsx/regular/1.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/1.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="001_0" scale={109.503}>
          <group name="model_skeleton_3">
            <group name="GLTF_created_0">
              <primitive object={nodes.GLTF_created_0_rootJoint} />
              <group name="Object_87001">
                <skinnedMesh name="Object_3001" geometry={nodes.Object_3001.geometry} material={materials['001Eye1']} skeleton={nodes.Object_3001.skeleton} />
                <skinnedMesh name="Object_3001_1" geometry={nodes.Object_3001_1.geometry} material={materials['001BodyB1']} skeleton={nodes.Object_3001_1.skeleton} />
                <skinnedMesh name="Object_3001_2" geometry={nodes.Object_3001_2.geometry} material={materials['001BodyA1']} skeleton={nodes.Object_3001_2.skeleton} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/1.glb')
