/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/1008.glb -o models/gltfjsx/regular/1008.jsx 
Author: Jakermates (https://sketchfab.com/jaydidleedoo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/miraidon-battle-form-pokemon-sv-bbbb6154715142d3a51b80def954d9ea
Title: Miraidon Battle Form Pokemon S&V
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/1008.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_227.geometry} material={materials.body_d_01} skeleton={nodes.Object_227.skeleton} />
      <skinnedMesh geometry={nodes.Object_229.geometry} material={materials.body_d_01} skeleton={nodes.Object_229.skeleton} />
      <skinnedMesh geometry={nodes.Object_231.geometry} material={materials.body_a_00} skeleton={nodes.Object_231.skeleton} />
      <skinnedMesh geometry={nodes.Object_233.geometry} material={materials.body_a_00} skeleton={nodes.Object_233.skeleton} />
      <skinnedMesh geometry={nodes.Object_235.geometry} material={materials.body_d_02} skeleton={nodes.Object_235.skeleton} />
      <skinnedMesh geometry={nodes.Object_241.geometry} material={materials.body_d_01} skeleton={nodes.Object_241.skeleton} />
      <skinnedMesh geometry={nodes.Object_237.geometry} material={materials.body_b} skeleton={nodes.Object_237.skeleton} />
      <skinnedMesh geometry={nodes.Object_238.geometry} material={materials.body_d_01} skeleton={nodes.Object_238.skeleton} />
      <skinnedMesh geometry={nodes.Object_239.geometry} material={materials.body_a_00} skeleton={nodes.Object_239.skeleton} />
      <skinnedMesh geometry={nodes.Object_243.geometry} material={materials.body_a_00} skeleton={nodes.Object_243.skeleton} />
      <skinnedMesh geometry={nodes.Object_244.geometry} material={materials.body_d_01} skeleton={nodes.Object_244.skeleton} />
      <skinnedMesh geometry={nodes.Object_246.geometry} material={materials.body_b} skeleton={nodes.Object_246.skeleton} />
      <skinnedMesh geometry={nodes.Object_247.geometry} material={materials.body_d_01} skeleton={nodes.Object_247.skeleton} />
      <skinnedMesh geometry={nodes.Object_249.geometry} material={materials.body_c} skeleton={nodes.Object_249.skeleton} />
      <skinnedMesh geometry={nodes.Object_251.geometry} material={materials.body_d_02} skeleton={nodes.Object_251.skeleton} />
      <skinnedMesh geometry={nodes.Object_253.geometry} material={materials.body_d_01} skeleton={nodes.Object_253.skeleton} />
      <skinnedMesh geometry={nodes.Object_254.geometry} material={materials.body_a_00} skeleton={nodes.Object_254.skeleton} />
      <skinnedMesh geometry={nodes.Object_256.geometry} material={materials.body_d_01} skeleton={nodes.Object_256.skeleton} />
      <skinnedMesh geometry={nodes.Object_258.geometry} material={materials.body_d_01} skeleton={nodes.Object_258.skeleton} />
      <skinnedMesh geometry={nodes.Object_259.geometry} material={materials.body_a_00} skeleton={nodes.Object_259.skeleton} />
      <skinnedMesh geometry={nodes.Object_261.geometry} material={materials.body_c} skeleton={nodes.Object_261.skeleton} />
      <skinnedMesh geometry={nodes.Object_263.geometry} material={materials.body_b} skeleton={nodes.Object_263.skeleton} />
      <skinnedMesh geometry={nodes.Object_264.geometry} material={materials.body_d_01} skeleton={nodes.Object_264.skeleton} />
      <skinnedMesh geometry={nodes.Object_265.geometry} material={materials.body_d_01} skeleton={nodes.Object_265.skeleton} />
      <skinnedMesh geometry={nodes.Object_267.geometry} material={materials.body_d_01} skeleton={nodes.Object_267.skeleton} />
      <skinnedMesh geometry={nodes.Object_269.geometry} material={materials.body_a_00} skeleton={nodes.Object_269.skeleton} />
      <skinnedMesh geometry={nodes.Object_271.geometry} material={materials.body_c} skeleton={nodes.Object_271.skeleton} />
      <skinnedMesh geometry={nodes.Object_273.geometry} material={materials.material} skeleton={nodes.Object_273.skeleton} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/1008.glb')
