/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/1018.glb -o models/gltfjsx/regular/1018.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 1018(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/1018.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.pm1132_00_00} />
      <primitive object={nodes.origin} />
      <primitive object={nodes.lod_group} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <skinnedMesh geometry={nodes.pm1132_00_00_body_a_mesh_shape_mesh.geometry} material={materials.body_a_01} skeleton={nodes.pm1132_00_00_body_a_mesh_shape_mesh.skeleton} />
        <skinnedMesh geometry={nodes.pm1132_00_00_body_a_mesh_shape_mesh_1.geometry} material={materials.body_a_00} skeleton={nodes.pm1132_00_00_body_a_mesh_shape_mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.pm1132_00_00_body_a_mesh_shape_mesh_2.geometry} material={materials.body_b_01} skeleton={nodes.pm1132_00_00_body_a_mesh_shape_mesh_2.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm1132_00_00_effect_b_mesh_shape.geometry} material={materials.eff_a_00} skeleton={nodes.pm1132_00_00_effect_b_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <skinnedMesh geometry={nodes.pm1132_00_00_head_mesh_shape_mesh.geometry} material={materials.body_a_01} skeleton={nodes.pm1132_00_00_head_mesh_shape_mesh.skeleton} />
        <skinnedMesh geometry={nodes.pm1132_00_00_head_mesh_shape_mesh_1.geometry} material={materials.r_eye} skeleton={nodes.pm1132_00_00_head_mesh_shape_mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.pm1132_00_00_head_mesh_shape_mesh_2.geometry} material={materials.r_eye} skeleton={nodes.pm1132_00_00_head_mesh_shape_mesh_2.skeleton} />
        <skinnedMesh geometry={nodes.pm1132_00_00_head_mesh_shape_mesh_3.geometry} material={materials.body_a_00} skeleton={nodes.pm1132_00_00_head_mesh_shape_mesh_3.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm1132_00_00_helmet_mesh_shape.geometry} material={materials.body_a_01} skeleton={nodes.pm1132_00_00_helmet_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <skinnedMesh geometry={nodes.pm1132_00_00_left_leg_mesh_shape_mesh.geometry} material={materials.body_a_01} skeleton={nodes.pm1132_00_00_left_leg_mesh_shape_mesh.skeleton} />
        <skinnedMesh geometry={nodes.pm1132_00_00_left_leg_mesh_shape_mesh_1.geometry} material={materials.body_a_00} skeleton={nodes.pm1132_00_00_left_leg_mesh_shape_mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.pm1132_00_00_left_leg_mesh_shape_mesh_2.geometry} material={materials.body_b_01} skeleton={nodes.pm1132_00_00_left_leg_mesh_shape_mesh_2.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm1132_00_00_neck_mesh_shape.geometry} material={materials.body_a_00} skeleton={nodes.pm1132_00_00_neck_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <skinnedMesh geometry={nodes.pm1132_00_00_right_leg_mesh_shape_mesh.geometry} material={materials.body_a_01} skeleton={nodes.pm1132_00_00_right_leg_mesh_shape_mesh.skeleton} />
        <skinnedMesh geometry={nodes.pm1132_00_00_right_leg_mesh_shape_mesh_1.geometry} material={materials.body_a_00} skeleton={nodes.pm1132_00_00_right_leg_mesh_shape_mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.pm1132_00_00_right_leg_mesh_shape_mesh_2.geometry} material={materials.body_b_01} skeleton={nodes.pm1132_00_00_right_leg_mesh_shape_mesh_2.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm1132_00_00_teeth_mesh_shape.geometry} material={materials.body_a_00} skeleton={nodes.pm1132_00_00_teeth_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/1018.glb')
