/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/109.glb -o models/gltfjsx/regular/109.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 109(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/109.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cone_Material004_0.geometry} material={materials.PaletteMaterial001} position={[-0.402, 1.894, 0.848]} rotation={[-Math.PI / 2, 0.139, -Math.PI]} />
      <mesh geometry={nodes.Sphere007_Material006_0.geometry} material={materials.PaletteMaterial002} position={[-1.574, 3.185, -0.303]} rotation={[-Math.PI / 2, -0.231, -Math.PI]} scale={[0.449, 0.449, 0.384]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/109.glb')
