/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/149.glb -o models/gltfjsx/regular/149.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/149.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <primitive object={nodes.Spine1} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Dragonite_1.geometry} material={materials['Material #207']} skeleton={nodes.Dragonite_1.skeleton} />
        <skinnedMesh geometry={nodes.Dragonite_2.geometry} material={materials['Material #208']} skeleton={nodes.Dragonite_2.skeleton} />
        <skinnedMesh geometry={nodes.Dragonite_3.geometry} material={materials['Material #209']} skeleton={nodes.Dragonite_3.skeleton} />
        <skinnedMesh geometry={nodes.Dragonite_4.geometry} material={materials['Material #210']} skeleton={nodes.Dragonite_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/149.glb')
