/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/161.glb -o models/gltfjsx/regular/161.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/161.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_Ears_0.geometry} material={materials.Ears} position={[0.023, 8.921, -0.077]} rotation={[-1.606, 0.283, 0.009]} scale={0.868} />
      <mesh geometry={nodes.Cube001_Feet_0.geometry} material={materials.Feet} position={[0.023, 3.811, -0.103]} rotation={[-1.302, -0.288, 0.786]} scale={0.868} />
      <mesh geometry={nodes.Cube002_Tail_0.geometry} material={materials.Tail} position={[0.023, 3.045, -0.332]} rotation={[-Math.PI / 2, 0, 0]} scale={0.868} />
      <mesh geometry={nodes.Sphere_Bod_0.geometry} material={materials.material} position={[0.023, 6.342, 0.016]} rotation={[-Math.PI / 2, 0, 0]} scale={0.868} />
      <mesh geometry={nodes.Sphere001_EyEs_0.geometry} material={materials.EyEs} position={[0.023, 7.778, 1.03]} rotation={[-0.763, 0.206, 0.017]} scale={0.868} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/161.glb')
