/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/17.glb -o models/gltfjsx/regular/17.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/17.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes['005_Hips']} />
      <primitive object={nodes['036_Spine1']} />
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Pidgeotto_1.geometry} material={materials.BodyA00} skeleton={nodes.Pidgeotto_1.skeleton} />
        <skinnedMesh geometry={nodes.Pidgeotto_2.geometry} material={materials.Eye} skeleton={nodes.Pidgeotto_2.skeleton} />
        <skinnedMesh geometry={nodes.Pidgeotto_3.geometry} material={materials.BodyB01} skeleton={nodes.Pidgeotto_3.skeleton} />
        <skinnedMesh geometry={nodes.Pidgeotto_4.geometry} material={materials.LIris} skeleton={nodes.Pidgeotto_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/17.glb')
