/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/174.glb -o models/gltfjsx/regular/174.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/igglybuff-eb434d6210e94307a155fb664c7ce6d8
Title: Igglybuff
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 174(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/174.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials['Eye_001-material']} skeleton={nodes.Object_6.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials['Body_001-material']} skeleton={nodes.Object_8.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials['Mouth_001-material']} skeleton={nodes.Object_10.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/174.glb')
