/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/177.glb -o models/gltfjsx/regular/177.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 177(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/177.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body_0.geometry} material={materials.default3} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.body_1.geometry} material={materials.mat45} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.body_2.geometry} material={materials.mat46} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.leg_l_0.geometry} material={materials._mat57} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.leg_l_1.geometry} material={materials._mat58} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.wing_l_0.geometry} material={materials._mat52} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.wing_l_1.geometry} material={materials._mat53} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/177.glb')
