/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/20.glb -o models/gltfjsx/regular/20.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 20(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/20.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes['004_Hips']} />
      <primitive object={nodes['038_Spine']} />
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Raticate_F_1.geometry} material={materials.Body00} skeleton={nodes.Raticate_F_1.skeleton} />
        <skinnedMesh geometry={nodes.Raticate_F_2.geometry} material={materials.Eye} skeleton={nodes.Raticate_F_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/20.glb')
