/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/234.glb -o models/gltfjsx/regular/234.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stantler-5718f76a99614525b93d5d96c880baf1
Title: Stantler
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 234(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/234.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_3.geometry} material={materials.eye_mat} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.body_mat} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.mouth_mat} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/234.glb')
