/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/271.glb -o models/gltfjsx/regular/271.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/271.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="hasuburero_10" rotation={[Math.PI / 2, 0, 0]} scale={1.633}>
          <primitive object={nodes.PG_root} />
        </group>
        <group name="hasuburero_10001" rotation={[Math.PI / 2, 0, 0]} scale={1.633}>
          <skinnedMesh name="hasuburero_10_1" geometry={nodes.hasuburero_10_1.geometry} material={materials.body} skeleton={nodes.hasuburero_10_1.skeleton} />
          <skinnedMesh name="hasuburero_10_2" geometry={nodes.hasuburero_10_2.geometry} material={materials.eye} skeleton={nodes.hasuburero_10_2.skeleton} />
          <skinnedMesh name="hasuburero_10_3" geometry={nodes.hasuburero_10_3.geometry} material={materials.mouth} skeleton={nodes.hasuburero_10_3.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/271.glb')
