/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/274.glb -o models/gltfjsx/regular/274.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 274(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/274.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <primitive object={nodes.Spine} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.NuzleafF_1.geometry} material={materials['Material #61']} skeleton={nodes.NuzleafF_1.skeleton} />
        <skinnedMesh geometry={nodes.NuzleafF_2.geometry} material={materials['Material #62']} skeleton={nodes.NuzleafF_2.skeleton} />
        <skinnedMesh geometry={nodes.NuzleafF_3.geometry} material={materials['Material #63']} skeleton={nodes.NuzleafF_3.skeleton} />
        <skinnedMesh geometry={nodes.NuzleafF_4.geometry} material={materials['Material #64']} skeleton={nodes.NuzleafF_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/274.glb')
