/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/286.glb -o models/gltfjsx/regular/286.jsx 
Author: Nardeol (https://sketchfab.com/Nardeol)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chapignon-fan-art-97c08332304041e6ac198cb7460926f0
Title: Chapignon fan art
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 286(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/286.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere_Material014_0.geometry} material={materials.PaletteMaterial001} position={[-2278.556, -3613.939, 5046.429]} rotation={[-1.46, -0.025, -0.786]} scale={[1467.516, 1467.516, 1467.517]} />
      <mesh geometry={nodes.Sphere_Material004_0.geometry} material={materials.PaletteMaterial002} position={[-2278.556, -3613.939, 5046.429]} rotation={[-1.46, -0.025, -0.786]} scale={[1467.516, 1467.516, 1467.517]} />
      <mesh geometry={nodes.Sphere_Material002_0.geometry} material={materials.PaletteMaterial003} position={[-2278.556, -3613.939, 5046.429]} rotation={[-1.46, -0.025, -0.786]} scale={[1467.516, 1467.516, 1467.517]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/286.glb')
