/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/288.glb -o models/gltfjsx/regular/288.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 288(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/288.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0288_00_00_body_mesh_shape_lod2_body_a_00.geometry} material={materials['body_a_00.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0288_00_00_body_mesh_shape_lod2_body_b.geometry} material={materials['body_b.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0288_00_00_eye_mesh_shape_lod2_l_eye.geometry} material={materials['l_eye.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Black} position={[0.094, 1.199, 0.44]} rotation={[-0.199, 0.48, -0.795]} scale={[-0.02, -0.02, -0.004]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/288.glb')
