/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/333.glb -o models/gltfjsx/regular/333.jsx 
Author: kuayarts (https://sketchfab.com/kuayarts)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-swablu-cloud-14cbf9c2a41644b99335a21e1a1f88ed
Title: Pokemon Swablu - Cloud
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/333.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Wablu_Body_0.geometry} material={materials.Body} position={[-0.011, 0.689, -0.009]} rotation={[-1.54, -0.088, 0.367]} scale={0.625} />
      <mesh geometry={nodes.Outlines_Outlines_0.geometry} material={materials.Outlines} position={[-0.011, 0.689, -0.009]} rotation={[-1.54, -0.088, 0.367]} scale={0.625} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/333.glb')
