/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/338.glb -o models/gltfjsx/regular/338.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 338(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/338.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Waist} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Solrock_1.geometry} material={materials['Material #59']} skeleton={nodes.Solrock_1.skeleton} />
        <skinnedMesh geometry={nodes.Solrock_2.geometry} material={materials['Material #60']} skeleton={nodes.Solrock_2.skeleton} />
        <skinnedMesh geometry={nodes.Solrock_3.geometry} material={materials['Material #61']} skeleton={nodes.Solrock_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/338.glb')
