/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/379.glb -o models/gltfjsx/regular/379.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 379(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/379.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Registeel_Material001_0.geometry} material={materials['Material.005']} position={[0.033, 1.678, 0.465]} rotation={[-2.394, 0.243, -2.875]} scale={[0.098, 0.098, 0.095]} />
      <mesh geometry={nodes.Registeel_Material002_0.geometry} material={materials['Material.004']} position={[0.033, 1.678, 0.465]} rotation={[-2.394, 0.243, -2.875]} scale={[0.098, 0.098, 0.095]} />
      <mesh geometry={nodes.Registeel_Material003_0.geometry} material={materials['Material.006']} position={[0.033, 1.678, 0.465]} rotation={[-2.394, 0.243, -2.875]} scale={[0.098, 0.098, 0.095]} />
      <mesh geometry={nodes.Registeel_Material009_0.geometry} material={materials['Material.009']} position={[0.033, 1.678, 0.465]} rotation={[-2.394, 0.243, -2.875]} scale={[0.098, 0.098, 0.095]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/379.glb')
