/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/403.glb -o models/gltfjsx/regular/403.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shinx-6c827b4537644e14ba901a0289a80219
Title: Shinx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 403(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/403.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.Material__323} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Material__324} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Material__322} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/403.glb')
