/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/424.glb -o models/gltfjsx/regular/424.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ambipom-b88583acb98f41c6908d29e336a69480
Title: Ambipom
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/424.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.EtebothDh} rotation={[Math.PI, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.EtebothEyeDh} rotation={[Math.PI, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.EtebothMouthDh} rotation={[Math.PI, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/424.glb')
