/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/43.glb -o models/gltfjsx/regular/43.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 43(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/43.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes['003_Waist']} />
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Oodish_1.geometry} material={materials.Body} skeleton={nodes.Oodish_1.skeleton} />
        <skinnedMesh geometry={nodes.Oodish_2.geometry} material={materials.Mouth} skeleton={nodes.Oodish_2.skeleton} />
        <skinnedMesh geometry={nodes.Oodish_3.geometry} material={materials.Eye} skeleton={nodes.Oodish_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/43.glb')
