/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/456.glb -o models/gltfjsx/regular/456.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/456.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_0.geometry} material={materials.Mouth} rotation={[Math.PI / 2, 0, 0]} scale={7.91} />
      <mesh geometry={nodes.Object_1.geometry} material={materials.Body} rotation={[Math.PI / 2, 0, 0]} scale={7.91} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.Eye} rotation={[Math.PI / 2, 0, 0]} scale={7.91} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/456.glb')
