/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/485.glb -o models/gltfjsx/regular/485.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/heatran-17a646503fb648d189a8527743cd62f6
Title: Heatran
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/485.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.VisualMaterial0} skeleton={nodes.Object_6.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.VisualMaterial10} skeleton={nodes.Object_8.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.VisualMaterial20} skeleton={nodes.Object_10.skeleton} scale={0.01} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/485.glb')
