/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/496.glb -o models/gltfjsx/regular/496.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/496.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <primitive object={nodes.Spine1} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Servine_1.geometry} material={materials['Material #71']} skeleton={nodes.Servine_1.skeleton} />
        <skinnedMesh geometry={nodes.Servine_2.geometry} material={materials['Material #72']} skeleton={nodes.Servine_2.skeleton} />
        <skinnedMesh geometry={nodes.Servine_3.geometry} material={materials['Material #73']} skeleton={nodes.Servine_3.skeleton} />
        <skinnedMesh geometry={nodes.Servine_4.geometry} material={materials['Material #74']} skeleton={nodes.Servine_4.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.Servine_LVine.geometry} material={materials['Material #71']} skeleton={nodes.Servine_LVine.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Servine_RVine.geometry} material={materials['Material #71']} skeleton={nodes.Servine_RVine.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/496.glb')
