/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/509.glb -o models/gltfjsx/regular/509.jsx 
Author: seth the yutyrannus (https://sketchfab.com/slang107123456789)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/purrloin-9f3e020ee81b4925b3d26d43d88ed16b
Title: Purrloin
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 509(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/509.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_112.geometry} material={materials.material} skeleton={nodes.Object_112.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_113.geometry} material={materials.material_1} skeleton={nodes.Object_113.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_114.geometry} material={materials.material_2} skeleton={nodes.Object_114.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_115.geometry} material={materials.material_2} skeleton={nodes.Object_115.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_116.geometry} material={materials.material_2} skeleton={nodes.Object_116.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_117.geometry} material={materials.material_2} skeleton={nodes.Object_117.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_118.geometry} material={materials.material_2} skeleton={nodes.Object_118.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_119.geometry} material={materials.material_2} skeleton={nodes.Object_119.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_120.geometry} material={materials.material_8} skeleton={nodes.Object_120.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_121.geometry} material={materials.material_8} skeleton={nodes.Object_121.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_122.geometry} material={materials.material_8} skeleton={nodes.Object_122.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_123.geometry} material={materials.material_8} skeleton={nodes.Object_123.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_124.geometry} material={materials.material_8} skeleton={nodes.Object_124.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_125.geometry} material={materials.material_8} skeleton={nodes.Object_125.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_126.geometry} material={materials.material_8} skeleton={nodes.Object_126.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/509.glb')
