/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/530.glb -o models/gltfjsx/regular/530.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 530(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/530.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['DoryuzuBodyNl.001']} rotation={[Math.PI / 2, 1.563, Math.PI / 2]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials['DoryuzuEyeNl.001']} rotation={[Math.PI / 2, 1.563, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/530.glb')
