/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/548.glb -o models/gltfjsx/regular/548.jsx 
Author: Cabblege (https://sketchfab.com/Cabblege)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/molly-molly-the-petilil-3d-model-f261da05f11742039ba25f5c9dcfe86a
Title: Molly - Molly the Petilil 3d Model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 548(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/548.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.churine_body} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/548.glb')
