/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/550.glb -o models/gltfjsx/regular/550.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/550.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.BassraoR} />
      <skinnedMesh geometry={nodes.mesh0000.geometry} material={materials['BassraoREyeNl.001']} skeleton={nodes.mesh0000.skeleton} rotation={[-0.011, 0, 0]} />
      <skinnedMesh geometry={nodes.mesh0001.geometry} material={materials['BassraoRNl.001']} skeleton={nodes.mesh0001.skeleton} rotation={[-0.011, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/550.glb')
