/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/56.glb -o models/gltfjsx/regular/56.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 56(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/56.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes['003_Waist']} />
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Mankey_1.geometry} material={materials.BodyDodo_Hair} skeleton={nodes.Mankey_1.skeleton} />
        <skinnedMesh geometry={nodes.Mankey_2.geometry} material={materials.Eye} skeleton={nodes.Mankey_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/56.glb')
