/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/576.glb -o models/gltfjsx/regular/576.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gothitelle-7347a7cbd2334b2dbe05767c2389db52
Title: Gothitelle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 576(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/576.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.GothiruselleBodyNl} rotation={[-Math.PI / 2, 1.57, -1.562]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.GothiruselleEyeNl} rotation={[-Math.PI / 2, 1.57, -1.562]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/576.glb')
