/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/605.glb -o models/gltfjsx/regular/605.jsx 
Author: thelaughingdingo (https://sketchfab.com/thelaughingdingo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/elgyem-pokemon-286000ad0fc946d3ba68a310e841cc72
Title: Elgyem (Pokemon)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 605(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/605.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Yellow} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.material} />
      <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Green} />
      <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.lambert6} />
      <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Elgy_Body} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/605.glb')
