/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/607.glb -o models/gltfjsx/regular/607.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/litwick-37afe722c71a4a0d873eeb647f31b3f2
Title: Litwick
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 607(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/607.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.HitomoshiBodyNl} rotation={[Math.PI, 1.564, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.HitomoshiEyeNl} rotation={[Math.PI, 1.564, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.HitomoshiMouthNl} rotation={[Math.PI, 1.564, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/607.glb')
