/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/630.glb -o models/gltfjsx/regular/630.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mandibuzz-4847b0393bdf4098a02c042ed38a106b
Title: Mandibuzz
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 630(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/630.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.VulginaEyeNl} rotation={[Math.PI, 1.564, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.VulginaNl} rotation={[Math.PI, 1.564, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/630.glb')
