/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/650.glb -o models/gltfjsx/regular/650.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/650.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <primitive object={nodes.Spine1} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Chespin_1.geometry} material={materials['Material #10']} skeleton={nodes.Chespin_1.skeleton} />
        <skinnedMesh geometry={nodes.Chespin_2.geometry} material={materials['Material #11']} skeleton={nodes.Chespin_2.skeleton} />
        <skinnedMesh geometry={nodes.Chespin_3.geometry} material={materials['Material #12']} skeleton={nodes.Chespin_3.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.Chespin_LowerQuills.geometry} material={materials['Material #10']} skeleton={nodes.Chespin_LowerQuills.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Chespin_UpperQuills.geometry} material={materials['Material #10']} skeleton={nodes.Chespin_UpperQuills.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Chespin_LowerSpikes.geometry} material={materials['Material #10']} skeleton={nodes.Chespin_LowerSpikes.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Chespin_UpperSpikes.geometry} material={materials['Material #10']} skeleton={nodes.Chespin_UpperSpikes.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/650.glb')
