/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/668-F.glb -o models/gltfjsx/regular/668-F.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 668-F(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/668-F.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <primitive object={nodes.Spine1} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.PyroarF_1.geometry} material={materials['Material #531']} skeleton={nodes.PyroarF_1.skeleton} />
        <skinnedMesh geometry={nodes.PyroarF_2.geometry} material={materials['Material #532']} skeleton={nodes.PyroarF_2.skeleton} />
        <skinnedMesh geometry={nodes.PyroarF_3.geometry} material={materials['Material #533']} skeleton={nodes.PyroarF_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/668-F.glb')
