/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/670.glb -o models/gltfjsx/regular/670.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 670(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/670.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.FeelerD} />
      <primitive object={nodes.LFeelerD1} />
      <primitive object={nodes.LFeelerD2} />
      <primitive object={nodes.RFeelerD1} />
      <primitive object={nodes.RFeelerD2} />
      <primitive object={nodes.Hips} />
      <primitive object={nodes.Spine} />
      <primitive object={nodes.FeelerF1} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Floette_1.geometry} material={materials.Body} skeleton={nodes.Floette_1.skeleton} />
        <skinnedMesh geometry={nodes.Floette_2.geometry} material={materials.Eye} skeleton={nodes.Floette_2.skeleton} />
        <skinnedMesh geometry={nodes.Floette_3.geometry} material={materials.Mouth} skeleton={nodes.Floette_3.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.Floette_Flower.geometry} material={materials.Flower} skeleton={nodes.Floette_Flower.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Floette_FlowerPetals.geometry} material={materials.Flower} skeleton={nodes.Floette_FlowerPetals.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Floette_FlowerBulb.geometry} material={materials.Flower} skeleton={nodes.Floette_FlowerBulb.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Floette_Petals.geometry} material={materials.Flower} skeleton={nodes.Floette_Petals.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/670.glb')
