/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/676.glb -o models/gltfjsx/regular/676.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/676.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <primitive object={nodes.Spine1} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Furfrou_1.geometry} material={materials.BodyA} skeleton={nodes.Furfrou_1.skeleton} />
        <skinnedMesh geometry={nodes.Furfrou_2.geometry} material={materials.Eye} skeleton={nodes.Furfrou_2.skeleton} />
        <skinnedMesh geometry={nodes.Furfrou_3.geometry} material={materials.Mouth} skeleton={nodes.Furfrou_3.skeleton} />
        <skinnedMesh geometry={nodes.Furfrou_4.geometry} material={materials.BodyB} skeleton={nodes.Furfrou_4.skeleton} />
      </group>
      <skinnedMesh geometry={nodes['Furfrou_Eye1-2-3'].geometry} material={materials.BodyA} skeleton={nodes['Furfrou_Eye1-2-3'].skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes['Furfrou_Eye4-6'].geometry} material={materials.BodyA} skeleton={nodes['Furfrou_Eye4-6'].skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Furfrou_Eye5.geometry} material={materials.BodyA} skeleton={nodes.Furfrou_Eye5.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Furfrou_Eye7.geometry} material={materials.BodyA} skeleton={nodes.Furfrou_Eye7.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/676.glb')
