/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/681.glb -o models/gltfjsx/regular/681.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 681(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/681.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.FeelerA2} />
      <primitive object={nodes.FeelerB2} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Aegislash_1.geometry} material={materials['Material #10']} skeleton={nodes.Aegislash_1.skeleton} />
        <skinnedMesh geometry={nodes.Aegislash_2.geometry} material={materials['Material #11']} skeleton={nodes.Aegislash_2.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.AegislashShieldGuard.geometry} material={materials['Material #12']} skeleton={nodes.AegislashShieldGuard.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.AegislashShieldBlade.geometry} material={materials['Material #12']} skeleton={nodes.AegislashShieldBlade.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/681.glb')
