/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/682.glb -o models/gltfjsx/regular/682.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/682.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Waist} />
      <skinnedMesh geometry={nodes.Spritzee_EyelashesA.geometry} material={materials['Material #77']} skeleton={nodes.Spritzee_EyelashesA.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Spritzee_EyelashesB.geometry} material={materials['Material #77']} skeleton={nodes.Spritzee_EyelashesB.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Spritzee_EyelashesC.geometry} material={materials['Material #77']} skeleton={nodes.Spritzee_EyelashesC.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Spritzee_EyelashesD.geometry} material={materials['Material #77']} skeleton={nodes.Spritzee_EyelashesD.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Spritzee_EyelashesE.geometry} material={materials['Material #77']} skeleton={nodes.Spritzee_EyelashesE.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Spritzee_EyelashesF.geometry} material={materials['Material #77']} skeleton={nodes.Spritzee_EyelashesF.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Spritzee_EyelashesG.geometry} material={materials['Material #77']} skeleton={nodes.Spritzee_EyelashesG.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Spritzee_EyelashesH.geometry} material={materials['Material #77']} skeleton={nodes.Spritzee_EyelashesH.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Spritzee_1.geometry} material={materials['Material #76']} skeleton={nodes.Spritzee_1.skeleton} />
        <skinnedMesh geometry={nodes.Spritzee_2.geometry} material={materials['Material #77']} skeleton={nodes.Spritzee_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/682.glb')
