/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/688.glb -o models/gltfjsx/regular/688.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/688.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Waist} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Binacle_1.geometry} material={materials.BodyB} skeleton={nodes.Binacle_1.skeleton} />
        <skinnedMesh geometry={nodes.Binacle_2.geometry} material={materials.BodyA} skeleton={nodes.Binacle_2.skeleton} />
        <skinnedMesh geometry={nodes.Binacle_3.geometry} material={materials.Eye} skeleton={nodes.Binacle_3.skeleton} />
        <skinnedMesh geometry={nodes.Binacle_4.geometry} material={materials.Mouth} skeleton={nodes.Binacle_4.skeleton} />
        <skinnedMesh geometry={nodes.Binacle_5.geometry} material={materials.Iris} skeleton={nodes.Binacle_5.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/688.glb')
