/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/709.glb -o models/gltfjsx/regular/709.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 709(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/709.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips1} />
      <primitive object={nodes.Spine1} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Trevenant_1.geometry} material={materials.BodyA} skeleton={nodes.Trevenant_1.skeleton} />
        <skinnedMesh geometry={nodes.Trevenant_2.geometry} material={materials.BodyB} skeleton={nodes.Trevenant_2.skeleton} />
        <skinnedMesh geometry={nodes.Trevenant_3.geometry} material={materials.BodyC} skeleton={nodes.Trevenant_3.skeleton} />
        <skinnedMesh geometry={nodes.Trevenant_4.geometry} material={materials.Eye} skeleton={nodes.Trevenant_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/709.glb')
