/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/712.glb -o models/gltfjsx/regular/712.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 712(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/712.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Waist} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Bergmite_1.geometry} material={materials.Eye} skeleton={nodes.Bergmite_1.skeleton} />
        <skinnedMesh geometry={nodes.Bergmite_2.geometry} material={materials.BodyEnv} skeleton={nodes.Bergmite_2.skeleton} />
        <skinnedMesh geometry={nodes.Bergmite_3.geometry} material={materials.BodyEnv} skeleton={nodes.Bergmite_3.skeleton} />
        <skinnedMesh geometry={nodes.Bergmite_4.geometry} material={materials.Iris} skeleton={nodes.Bergmite_4.skeleton} />
        <skinnedMesh geometry={nodes.Bergmite_5.geometry} material={materials.BodyEnv} skeleton={nodes.Bergmite_5.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/712.glb')
