/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/721.glb -o models/gltfjsx/regular/721.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 721(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/721.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <primitive object={nodes.Spine} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Volcanion_1.geometry} material={materials.BodyB} skeleton={nodes.Volcanion_1.skeleton} />
        <skinnedMesh geometry={nodes.Volcanion_2.geometry} material={materials.Eye} skeleton={nodes.Volcanion_2.skeleton} />
        <skinnedMesh geometry={nodes.Volcanion_3.geometry} material={materials.BodyA} skeleton={nodes.Volcanion_3.skeleton} />
        <skinnedMesh geometry={nodes.Volcanion_4.geometry} material={materials.Iris} skeleton={nodes.Volcanion_4.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.Volcanion_ClampsA.geometry} material={materials.BodyB} skeleton={nodes.Volcanion_ClampsA.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Volcanion_ClampsB.geometry} material={materials.BodyB} skeleton={nodes.Volcanion_ClampsB.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/721.glb')
