/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/726.glb -o models/gltfjsx/regular/726.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/726.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.pm0845_00} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh.geometry} material={materials.BodyA} skeleton={nodes.Mesh.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials.Eye} skeleton={nodes.Mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_2.geometry} material={materials.Mouth} skeleton={nodes.Mesh_2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_3.geometry} material={materials.LIris} skeleton={nodes.Mesh_3.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_4.geometry} material={materials.LIris} skeleton={nodes.Mesh_4.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_5.geometry} material={materials.BodyC} skeleton={nodes.Mesh_5.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.Torracat_Collar.geometry} material={materials.BodyC} skeleton={nodes.Torracat_Collar.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.Torracat_CollarB_Layer1.geometry} material={materials.FireStenA1} skeleton={nodes.Torracat_CollarB_Layer1.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.Torracat_CollarB_Layer2.geometry} material={materials.FireStenA2} skeleton={nodes.Torracat_CollarB_Layer2.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.Torracat_CollarB_Layer3.geometry} material={materials.BodyC} skeleton={nodes.Torracat_CollarB_Layer3.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.Torracat_Teeth1.geometry} material={materials.BodyA} skeleton={nodes.Torracat_Teeth1.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes['Torracat_Teeth2-3'].geometry} material={materials.BodyA} skeleton={nodes['Torracat_Teeth2-3'].skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.Torracat_Teeth5.geometry} material={materials.BodyA} skeleton={nodes.Torracat_Teeth5.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.Torracat_Teeth7.geometry} material={materials.BodyA} skeleton={nodes.Torracat_Teeth7.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/726.glb')
