/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/738.glb -o models/gltfjsx/regular/738.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vikavolt-e29987302b7646e0a40289778095f84d
Title: Vikavolt
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/738.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials['Wings-material']} skeleton={nodes.Object_6.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials['Wings-material']} skeleton={nodes.Object_8.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials['pm0838_00_Eye1_tga_png-material']} skeleton={nodes.Object_10.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/738.glb')
