/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/739.glb -o models/gltfjsx/regular/739.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crabrawler-1a350b4f678c47d9b44e695362fed2ff
Title: Crabrawler
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 739(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/739.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_3.geometry} material={materials['pm0859_00_Body_tga_png-material']} />
      <mesh geometry={nodes.Object_4.geometry} material={materials['pm0859_00_Eye_tga_png-material']} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/739.glb')
