/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/740.glb -o models/gltfjsx/regular/740.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/740.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0860_00_00_body_mesh_shape_lod2_body_a.geometry} material={materials.body_a} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0860_00_00_body_mesh_shape_lod2_body_b.geometry} material={materials.body_b} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0860_00_00_body_mesh_shape_lod2_l_eye.geometry} material={materials.l_eye} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/740.glb')
