/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/746.glb -o models/gltfjsx/regular/746.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/746.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.instance_0.geometry} material={materials.pm0820_11_Eye1_tga} position={[0, 0.135, -0.195]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.instance_0002.geometry} material={materials.pm0820_11_Body1_tga} position={[0, 0.135, -0.195]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/746.glb')
