/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/762.glb -o models/gltfjsx/regular/762.jsx 
Author: seth the yutyrannus (https://sketchfab.com/slang107123456789)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/steenee-1ab4633bc1684492996c9dbfc7c0c8fb
Title: steenee
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 762(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/762.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_59.geometry} material={materials['Material.003']} skeleton={nodes.Object_59.skeleton} scale={0.192} />
      <skinnedMesh geometry={nodes.Object_61.geometry} material={materials['Material.001']} skeleton={nodes.Object_61.skeleton} scale={0.192} />
      <skinnedMesh geometry={nodes.Object_63.geometry} material={materials['Material.002']} skeleton={nodes.Object_63.skeleton} scale={0.192} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/762.glb')
