/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/766.glb -o models/gltfjsx/regular/766.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 766(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/766.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0815_00_00_body_mesh_shape_body_a_01.geometry} material={materials.body_a_01} position={[0, 0.609, 0.044]} rotation={[1.087, 0, 0]} />
      <mesh geometry={nodes.pm0815_00_00_body_mesh_shape_body_b_00.geometry} material={materials.body_b_00} position={[0, 0.609, 0.044]} rotation={[1.087, 0, 0]} />
      <mesh geometry={nodes.pm0815_00_00_eye_mesh_shape_l_eye.geometry} material={materials.l_eye} position={[0, 0.609, 0.044]} rotation={[1.087, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/766.glb')
