/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/770.glb -o models/gltfjsx/regular/770.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/770.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={1} decay={2} position={[6.48, 24.793, 20.624]} rotation={[0, 1.26, 0]} target={nodes.DirectionalLight.target}>
        <primitive object={nodes.DirectionalLight.target} position={[0, 0, -1]} />
      </directionalLight>
      <directionalLight intensity={1} decay={2} position={[-15.807, 26.409, -7.961]} target={nodes.DirectionalLight_2.target}>
        <primitive object={nodes.DirectionalLight_2.target} position={[0, 0, -1]} />
      </directionalLight>
      <mesh geometry={nodes.Cube_Material006_0.geometry} material={materials.PaletteMaterial001} position={[-1.429, 1.292, 0.535]} rotation={[-Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.mesh_1.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.mesh_1.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_2.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.mesh_2.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_3.geometry, materials.PaletteMaterial001, 14]} instanceMatrix={nodes.mesh_3.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/770.glb')
