/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/791.glb -o models/gltfjsx/regular/791.jsx 
Author: Znvne179 (https://sketchfab.com/daychiefaden8)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/solgaleo-dc8420f392bf4cc789a80abec990b8dc
Title: Solgaleo
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 791(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/791.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.BodyA} skeleton={nodes.Object_6.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.BodyB} skeleton={nodes.Object_7.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.material} skeleton={nodes.Object_8.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.BodyD} skeleton={nodes.Object_9.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.BodyD_Trans} skeleton={nodes.Object_10.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.Material_42} skeleton={nodes.Object_12.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.Material_53} skeleton={nodes.Object_14.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.Material_53} skeleton={nodes.Object_16.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.BodyC} skeleton={nodes.Object_18.skeleton} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/791.glb')
