/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/793.glb -o models/gltfjsx/regular/793.jsx 
Author: LunaEagle (https://sketchfab.com/LunaEagle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lusamine-mother-beast-d1422b1a32154f7ebf95be074ed5309b
Title: Lusamine Mother Beast
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 793(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/793.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['assets_textures_tr0035_00_BodyB_tga_png.002']} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['assets_textures_tr0035_00_Eye_tga_png.002']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['assets_textures_tr0035_00_BodyC_tga_png.002']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['assets_textures_tr0035_00_BodyA_tga_png.002']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['assets_textures_tr0035_00_BodyE_tga_png.002']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['assets_textures_tr0035_00_BodyDcol_tga_png.002']} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/793.glb')
