/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/799.glb -o models/gltfjsx/regular/799.jsx 
Author: Forsaken AR Official (https://sketchfab.com/FNAF_AR_Official)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3ds-pokemon-ultra-sun-ultra-moon-799-guzzlor-49d324a61b064a32857ac90fdc92fe3b
Title: 3DS - Pokemon Ultra Sun Ultra Moon - 799 Guzzlor
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 799(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/799.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_3.geometry} material={materials['pm0876_00_BodyA_tga_png-material']} />
      <mesh geometry={nodes.Object_4.geometry} material={materials['pm0876_00_BodyB_tga_png-material']} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['pm0876_00_BodyC_tga_png-material']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['pm0876_00_Eye_tga_png-material']} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/799.glb')
