/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/804.glb -o models/gltfjsx/regular/804.jsx 
Author: Forsaken AR Official (https://sketchfab.com/FNAF_AR_Official)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3ds-pokemon-ultra-sun-ultra-moon-804-naganad-0948f6728fb94043bcfea54a90b0bec4
Title: 3DS - Pokemon Ultra Sun Ultra Moon - 804 Naganad
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/804.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials['pm0887_00_Body1_tga_png-material']} skeleton={nodes.Object_6.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials['pm0887_00_EyeInc_tga_png-material']} skeleton={nodes.Object_8.skeleton} scale={0.01} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/804.glb')
