/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/807.glb -o models/gltfjsx/regular/807.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 807(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/807.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials['pm0888_00_BodyB1_tga_png-material']} skeleton={nodes.Object_10.skeleton} rotation={[-1.687, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials['pm0888_00_Eye1_tga_png-material']} skeleton={nodes.Object_6.skeleton} rotation={[-1.687, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials['pm0888_00_BodyA1_tga_png-material']} skeleton={nodes.Object_8.skeleton} rotation={[-1.687, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/807.glb')
