/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/813.glb -o models/gltfjsx/regular/813.jsx 
Author: Nathan Leyens (https://sketchfab.com/leynat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scorbunny-model-24c1da4cfa384571b413ae77e7cf1247
Title: Scorbunny Model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 813(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/813.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface1_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} position={[0, 2.41, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/813.glb')
