/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/819.glb -o models/gltfjsx/regular/819.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/819.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.pm0909_00_00} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh.geometry} material={materials.Body} skeleton={nodes.Mesh.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials.Eye} skeleton={nodes.Mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_2.geometry} material={materials.Mouth} skeleton={nodes.Mesh_2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_3.geometry} material={materials.Body} skeleton={nodes.Mesh_3.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_4.geometry} material={materials.Body} skeleton={nodes.Mesh_4.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm0909_00_00_TailSkin.geometry} material={materials.Body} skeleton={nodes.pm0909_00_00_TailSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/819.glb')
