/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/820.glb -o models/gltfjsx/regular/820.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/820.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.pm0910_00_00} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh.geometry} material={materials.BodyA02Vco} skeleton={nodes.Mesh.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials.BodyA02Vco} skeleton={nodes.Mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_2.geometry} material={materials.Eye} skeleton={nodes.Mesh_2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_3.geometry} material={materials.BodyB} skeleton={nodes.Mesh_3.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_4.geometry} material={materials.BodyA02Vco} skeleton={nodes.Mesh_4.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm0910_00_00_ChigoASkin.geometry} material={materials.BodyC00Vco} skeleton={nodes.pm0910_00_00_ChigoASkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0910_00_00_ChigoBSkin.geometry} material={materials.BodyC00Vco} skeleton={nodes.pm0910_00_00_ChigoBSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0910_00_00_ChigoCSkin.geometry} material={materials.BodyC00Vco} skeleton={nodes.pm0910_00_00_ChigoCSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh004.geometry} material={materials.BodyC00Vco} skeleton={nodes.Mesh004.skeleton} />
        <skinnedMesh geometry={nodes.Mesh004_1.geometry} material={materials.BodyC00Vco} skeleton={nodes.Mesh004_1.skeleton} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh005.geometry} material={materials.BodyC00Vco} skeleton={nodes.Mesh005.skeleton} />
        <skinnedMesh geometry={nodes.Mesh005_1.geometry} material={materials.BodyC00Vco} skeleton={nodes.Mesh005_1.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm0910_00_00_NanaASkin.geometry} material={materials.BodyC00Vco} skeleton={nodes.pm0910_00_00_NanaASkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0910_00_00_NanaBSkin.geometry} material={materials.BodyC00Vco} skeleton={nodes.pm0910_00_00_NanaBSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/820.glb')
