/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/821.glb -o models/gltfjsx/regular/821.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 821(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/821.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.pm0918_00_00} />
      <skinnedMesh geometry={nodes.pm0918_00_00_BeakSkin.geometry} material={materials.BodyVco01} skeleton={nodes.pm0918_00_00_BeakSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh.geometry} material={materials.Eye} skeleton={nodes.Mesh.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials.BodyVco01} skeleton={nodes.Mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_2.geometry} material={materials.BodyVco01} skeleton={nodes.Mesh_2.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm0918_00_00_LWingCloseSkin.geometry} material={materials.BodyVco01} skeleton={nodes.pm0918_00_00_LWingCloseSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0918_00_00_LWingOpenSkin.geometry} material={materials.BodyVco01} skeleton={nodes.pm0918_00_00_LWingOpenSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0918_00_00_RWingCloseSkin.geometry} material={materials.BodyVco01} skeleton={nodes.pm0918_00_00_RWingCloseSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0918_00_00_RWingOpenSkin.geometry} material={materials.BodyVco01} skeleton={nodes.pm0918_00_00_RWingOpenSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0918_00_00_TongueSkin.geometry} material={materials.BodyVco01} skeleton={nodes.pm0918_00_00_TongueSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/821.glb')
