/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/832.glb -o models/gltfjsx/regular/832.jsx 
Author: Cubone0711 (https://sketchfab.com/Cubone0711)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nintendo-switch-pokemon-sword-shield-832-dub-057a631e93784ed19e5c6cbd14aa96c1
Title: Nintendo Switch - Pokemon Sword Shield - 832 Dub
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 832(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/832.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.BodyA01} skeleton={nodes.Object_6.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.BodyA00} skeleton={nodes.Object_8.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.material} skeleton={nodes.Object_9.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.BodyBVco01} skeleton={nodes.Object_11.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.BodyBVco01} skeleton={nodes.Object_13.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.BodyA00} skeleton={nodes.Object_15.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.BodyA01} skeleton={nodes.Object_16.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.BodyA00} skeleton={nodes.Object_18.skeleton} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/832.glb')
