/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/837.glb -o models/gltfjsx/regular/837.jsx 
Author: Forsaken AR Official (https://sketchfab.com/FNAF_AR_Official)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nintendo-switch-pokemon-sword-shield-837-rol-3ea1ffbf2c4441f5a20c136a11364794
Title: Nintendo Switch - Pokemon Sword Shield - 837 Rol
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 837(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/837.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.BodyA} skeleton={nodes.Object_6.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.EyeVco} skeleton={nodes.Object_7.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.BodyA} skeleton={nodes.Object_8.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.BodyBVco} skeleton={nodes.Object_10.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.BodyBVco} skeleton={nodes.Object_12.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.BodyBVco} skeleton={nodes.Object_14.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.BodyBVco} skeleton={nodes.Object_16.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.BodyBVco} skeleton={nodes.Object_18.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.BodyBVco} skeleton={nodes.Object_20.skeleton} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/837.glb')
