/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/838.glb -o models/gltfjsx/regular/838.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 838(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/838.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.pm0934_00_00} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh.geometry} material={materials.Eye} skeleton={nodes.Mesh.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials.BodyB00Inc} skeleton={nodes.Mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_2.geometry} material={materials.BodyA01EnvVco} skeleton={nodes.Mesh_2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_3.geometry} material={materials.BodyA01EnvVco} skeleton={nodes.Mesh_3.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerA00Skin.geometry} material={materials.BodyC00EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerA00Skin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerA01Skin.geometry} material={materials.BodyC01EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerA01Skin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerB00Skin.geometry} material={materials.BodyC00EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerB00Skin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerB01Skin.geometry} material={materials.BodyC01EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerB01Skin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerC00Skin.geometry} material={materials.BodyC00EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerC00Skin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerC01Skin.geometry} material={materials.BodyC01EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerC01Skin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerDSkin.geometry} material={materials.BodyC00EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerDSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerE00Skin.geometry} material={materials.BodyC00EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerE00Skin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerE01Skin.geometry} material={materials.BodyC01EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerE01Skin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerFSkin.geometry} material={materials.BodyC00EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerFSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerGSkin.geometry} material={materials.BodyC00EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerGSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerHSkin.geometry} material={materials.BodyC00EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerHSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerISkin.geometry} material={materials.BodyC00EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerISkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerJSkin.geometry} material={materials.BodyC00EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerJSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_FeelerKSkin.geometry} material={materials.BodyC00EnvIncVco} skeleton={nodes.pm0934_00_00_FeelerKSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_TeethA00Skin.geometry} material={materials.BodyB00Inc} skeleton={nodes.pm0934_00_00_TeethA00Skin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_TeethA01Skin.geometry} material={materials.BodyB02IncVco} skeleton={nodes.pm0934_00_00_TeethA01Skin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_TeethB00Skin.geometry} material={materials.BodyB00Inc} skeleton={nodes.pm0934_00_00_TeethB00Skin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0934_00_00_TeethB01Skin.geometry} material={materials.BodyB02IncVco} skeleton={nodes.pm0934_00_00_TeethB01Skin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/838.glb')
