/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/84.glb -o models/gltfjsx/regular/84.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 84(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/84.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Waist} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.DoduoF_1.geometry} material={materials.Body} skeleton={nodes.DoduoF_1.skeleton} />
        <skinnedMesh geometry={nodes.DoduoF_2.geometry} material={materials.EyeA} skeleton={nodes.DoduoF_2.skeleton} />
        <skinnedMesh geometry={nodes.DoduoF_3.geometry} material={materials.Body} skeleton={nodes.DoduoF_3.skeleton} />
        <skinnedMesh geometry={nodes.DoduoF_4.geometry} material={materials.EyeA} skeleton={nodes.DoduoF_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/84.glb')
