/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/849.glb -o models/gltfjsx/regular/849.jsx 
Author: LunaEagle (https://sketchfab.com/LunaEagle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toxtricity-5e310132cdb0488697e515a1b404260e
Title: Toxtricity
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 849(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/849.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials['pm0849_11_00-BodyA02']} skeleton={nodes.Object_168.skeleton} scale={0.5} />
        <skinnedMesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials['pm0849_11_00-BodyBInc']} skeleton={nodes.Object_170.skeleton} scale={0.5} />
        <skinnedMesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials['pm0849_11_00-BodyA02']} skeleton={nodes.Object_172.skeleton} scale={0.5} />
        <skinnedMesh name="Object_173" geometry={nodes.Object_173.geometry} material={materials['pm0849_11_00-BodyA02']} skeleton={nodes.Object_173.skeleton} scale={0.5} />
        <skinnedMesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials['pm0849_11_00-LEye']} skeleton={nodes.Object_174.skeleton} scale={0.5} />
        <skinnedMesh name="Object_175" geometry={nodes.Object_175.geometry} material={materials['pm0849_11_00-BodyA02']} skeleton={nodes.Object_175.skeleton} scale={0.5} />
        <skinnedMesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials['pm0849_11_00-LEye']} skeleton={nodes.Object_176.skeleton} scale={0.5} />
        <skinnedMesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials['pm0849_11_00-BodyA02']} skeleton={nodes.Object_178.skeleton} scale={0.5} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/849.glb')
