/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/862.glb -o models/gltfjsx/regular/862.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/862.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.5}>
          <primitive object={nodes.pm0862_00_31_prefab} />
          <group name="pm0862_00_31_BodySkin">
            <skinnedMesh name="pm0862_00_31_BodySkin_1" geometry={nodes.pm0862_00_31_BodySkin_1.geometry} material={materials['pm0862_00_31-BodyA00']} skeleton={nodes.pm0862_00_31_BodySkin_1.skeleton} />
            <skinnedMesh name="pm0862_00_31_BodySkin_2" geometry={nodes.pm0862_00_31_BodySkin_2.geometry} material={materials['pm0862_00_31-LEye']} skeleton={nodes.pm0862_00_31_BodySkin_2.skeleton} />
            <skinnedMesh name="pm0862_00_31_BodySkin_3" geometry={nodes.pm0862_00_31_BodySkin_3.geometry} material={materials['pm0862_00_31-BodyA00']} skeleton={nodes.pm0862_00_31_BodySkin_3.skeleton} />
            <skinnedMesh name="pm0862_00_31_BodySkin_4" geometry={nodes.pm0862_00_31_BodySkin_4.geometry} material={materials['pm0862_00_31-BodyA00']} skeleton={nodes.pm0862_00_31_BodySkin_4.skeleton} />
            <skinnedMesh name="pm0862_00_31_BodySkin_5" geometry={nodes.pm0862_00_31_BodySkin_5.geometry} material={materials['pm0862_00_31-BodyB00']} skeleton={nodes.pm0862_00_31_BodySkin_5.skeleton} />
            <skinnedMesh name="pm0862_00_31_BodySkin_6" geometry={nodes.pm0862_00_31_BodySkin_6.geometry} material={materials['pm0862_00_31-LEye']} skeleton={nodes.pm0862_00_31_BodySkin_6.skeleton} />
          </group>
          <skinnedMesh name="pm0862_00_31_LowerTeethSkin" geometry={nodes.pm0862_00_31_LowerTeethSkin.geometry} material={materials['pm0862_00_31-BodyB01']} skeleton={nodes.pm0862_00_31_LowerTeethSkin.skeleton} />
          <skinnedMesh name="pm0862_00_31_TongueSkin" geometry={nodes.pm0862_00_31_TongueSkin.geometry} material={materials['pm0862_00_31-BodyA00']} skeleton={nodes.pm0862_00_31_TongueSkin.skeleton} />
          <skinnedMesh name="pm0862_00_31_UpperTeethSkin" geometry={nodes.pm0862_00_31_UpperTeethSkin.geometry} material={materials['pm0862_00_31-BodyB01']} skeleton={nodes.pm0862_00_31_UpperTeethSkin.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/862.glb')
