/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/888.glb -o models/gltfjsx/regular/888.jsx 
Author: User 37564 (https://sketchfab.com/rhl89ryo)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/zacian-armor-pokemon-sword-2b1ce8a0b18540cb82d2b88eb6f00f79
Title: Zacian (Armor) [Pokemon Sword]
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/888.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <primitive object={nodes.GLTF_created_1_rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_7.skeleton} position={[0, 0.98, 2.057]} rotation={[-2.675, 0, Math.PI / 2]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_8.skeleton} position={[0, 0.98, 2.057]} rotation={[-2.675, 0, Math.PI / 2]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_9.skeleton} position={[0, 0.98, 2.057]} rotation={[-2.675, 0, Math.PI / 2]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_15.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_16.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_17.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_18.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_19.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_20.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_21.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_22.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_22.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_24.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_24.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_25.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_25.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_27.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_27.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_28.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_28.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_29.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_29.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_30.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_30.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_31.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_31.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_33.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_33.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_35.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Object_35.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_36.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_36.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_38.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_38.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_39.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_39.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_40.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_40.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_42.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_42.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_44.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_44.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_46.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_46.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
      <skinnedMesh geometry={nodes.Object_48.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_48.skeleton} position={[0, 1.335, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.415} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/888.glb')
