/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/890.glb -o models/gltfjsx/regular/890.jsx 
Author: LunaEagle (https://sketchfab.com/LunaEagle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eternatus-700d5fbbab114ada8cafe842d5ed2ad2
Title: Eternatus
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 890(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/890.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['pm0890_00_00-BodyBIncVco00']} skeleton={nodes.Object_13.skeleton} scale={0.5} />
        <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['pm0890_00_00-BodyBIncVco00']} skeleton={nodes.Object_14.skeleton} scale={0.5} />
        <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['pm0890_00_00-BodyA']} skeleton={nodes.Object_16.skeleton} scale={0.5} />
        <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['pm0890_00_00-BodyBIncVco00']} skeleton={nodes.Object_17.skeleton} scale={0.5} />
        <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['pm0890_00_00-BodyBIncVco00']} skeleton={nodes.Object_18.skeleton} scale={0.5} />
        <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials['pm0890_00_00-BodyBIncVco00']} skeleton={nodes.Object_19.skeleton} scale={0.5} />
        <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['pm0890_00_00-BodyBIncVco00']} skeleton={nodes.Object_20.skeleton} scale={0.5} />
        <skinnedMesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials['pm0890_00_00-BodyCEnv']} skeleton={nodes.Object_22.skeleton} scale={0.5} />
        <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['pm0890_00_00-BodyCEnv']} skeleton={nodes.Object_24.skeleton} scale={0.5} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/890.glb')
