/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/891.glb -o models/gltfjsx/regular/891.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 891(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/891.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.pm0982_00_00} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh001.geometry} material={materials.body_b} skeleton={nodes.Mesh001.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_1.geometry} material={materials.body_a} skeleton={nodes.Mesh001_1.skeleton} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh005.geometry} material={materials.body_b} skeleton={nodes.Mesh005.skeleton} />
        <skinnedMesh geometry={nodes.Mesh005_1.geometry} material={materials.body_a} skeleton={nodes.Mesh005_1.skeleton} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh009.geometry} material={materials.body_b} skeleton={nodes.Mesh009.skeleton} />
        <skinnedMesh geometry={nodes.Mesh009_1.geometry} material={materials.body_a} skeleton={nodes.Mesh009_1.skeleton} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh003.geometry} material={materials.l_eye} skeleton={nodes.Mesh003.skeleton} />
        <skinnedMesh geometry={nodes.Mesh003_1.geometry} material={materials.l_eye} skeleton={nodes.Mesh003_1.skeleton} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh007.geometry} material={materials.l_eye} skeleton={nodes.Mesh007.skeleton} />
        <skinnedMesh geometry={nodes.Mesh007_1.geometry} material={materials.l_eye} skeleton={nodes.Mesh007_1.skeleton} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh007.geometry} material={materials.l_eye} skeleton={nodes.Mesh007.skeleton} />
        <skinnedMesh geometry={nodes.Mesh007_1.geometry} material={materials.l_eye} skeleton={nodes.Mesh007_1.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm0982_00_00_eyelid_mesh_shape.geometry} material={materials.body_a} skeleton={nodes.pm0982_00_00_eyelid_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0982_00_00_eyelid_mesh_shape_lod1.geometry} material={materials.body_a} skeleton={nodes.pm0982_00_00_eyelid_mesh_shape_lod1.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0982_00_00_eyelid_mesh_shape_lod2.geometry} material={materials.body_a} skeleton={nodes.pm0982_00_00_eyelid_mesh_shape_lod2.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0982_00_00_hair_mesh_shape.geometry} material={materials.body_b} skeleton={nodes.pm0982_00_00_hair_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0982_00_00_hair_mesh_shape_lod1.geometry} material={materials.body_b} skeleton={nodes.pm0982_00_00_hair_mesh_shape_lod1.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm0982_00_00_hair_mesh_shape_lod2.geometry} material={materials.body_b} skeleton={nodes.pm0982_00_00_hair_mesh_shape_lod2.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/891.glb')
