/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/892.glb -o models/gltfjsx/regular/892.jsx 
Author: georgealejo380 (https://sketchfab.com/georgealejo380)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-home-urshifu-373da6e51a944de98f9015744a836bb5
Title: Pokemon HOME Urshifu
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/892.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_336" geometry={nodes.Object_336.geometry} material={materials['pm0892_12_00-BodyA00']} skeleton={nodes.Object_336.skeleton} scale={0.5} />
        <skinnedMesh name="Object_337" geometry={nodes.Object_337.geometry} material={materials['pm0892_12_00-BodyB']} skeleton={nodes.Object_337.skeleton} scale={0.5} />
        <skinnedMesh name="Object_338" geometry={nodes.Object_338.geometry} material={materials['pm0892_12_00-BodyB']} skeleton={nodes.Object_338.skeleton} scale={0.5} />
        <skinnedMesh name="Object_339" geometry={nodes.Object_339.geometry} material={materials['pm0892_12_00-LEye']} skeleton={nodes.Object_339.skeleton} scale={0.5} />
        <skinnedMesh name="Object_340" geometry={nodes.Object_340.geometry} material={materials['pm0892_12_00-BodyA00']} skeleton={nodes.Object_340.skeleton} scale={0.5} />
        <skinnedMesh name="Object_341" geometry={nodes.Object_341.geometry} material={materials['pm0892_12_00-LEye']} skeleton={nodes.Object_341.skeleton} scale={0.5} />
        <skinnedMesh name="Object_343" geometry={nodes.Object_343.geometry} material={materials['pm0892_12_00-BodyA00']} skeleton={nodes.Object_343.skeleton} scale={0.5} />
        <skinnedMesh name="Object_345" geometry={nodes.Object_345.geometry} material={materials['pm0892_12_00-BodyB']} skeleton={nodes.Object_345.skeleton} scale={0.5} />
        <skinnedMesh name="Object_347" geometry={nodes.Object_347.geometry} material={materials['pm0892_12_00-BodyA00']} skeleton={nodes.Object_347.skeleton} scale={0.5} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/892.glb')
