/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/898.glb -o models/gltfjsx/regular/898.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/898.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0898_13_00_BodyBOutSkin.geometry} material={materials['pm0898_13_00-BodyDInc']} position={[0.031, -0.793, 0]} rotation={[1.726, 0.019, 0.044]} />
      <mesh geometry={nodes.pm0898_13_00_CollarSkin.geometry} material={materials['pm0898_13_00-BodyCVco']} position={[0.031, -0.793, 0]} rotation={[1.726, 0.019, 0.044]} />
      <group position={[0.031, -0.793, 0]} rotation={[1.726, 0.019, 0.044]}>
        <mesh geometry={nodes.pm0898_13_00_BodyASkin_1.geometry} material={materials['pm0898_13_00-Mouth']} />
        <mesh geometry={nodes.pm0898_13_00_BodyASkin_2.geometry} material={materials['pm0898_13_00-LEye']} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/898.glb')
