/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/914.glb -o models/gltfjsx/regular/914.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/914.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.pm1018_00_00} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh002.geometry} material={materials.body_a_00} skeleton={nodes.Mesh002.skeleton} />
        <skinnedMesh geometry={nodes.Mesh002_1.geometry} material={materials.body_a_00} skeleton={nodes.Mesh002_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh002_2.geometry} material={materials.body_b_00} skeleton={nodes.Mesh002_2.skeleton} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh011.geometry} material={materials.body_a_00} skeleton={nodes.Mesh011.skeleton} />
        <skinnedMesh geometry={nodes.Mesh011_1.geometry} material={materials.body_a_00} skeleton={nodes.Mesh011_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh011_2.geometry} material={materials.body_b_00} skeleton={nodes.Mesh011_2.skeleton} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh020.geometry} material={materials.body_a_00} skeleton={nodes.Mesh020.skeleton} />
        <skinnedMesh geometry={nodes.Mesh020_1.geometry} material={materials.body_a_00} skeleton={nodes.Mesh020_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh020_2.geometry} material={materials.body_b_00} skeleton={nodes.Mesh020_2.skeleton} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh.geometry} material={materials.r_eye} skeleton={nodes.Mesh.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials.r_eye} skeleton={nodes.Mesh_1.skeleton} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh009.geometry} material={materials.r_eye} skeleton={nodes.Mesh009.skeleton} />
        <skinnedMesh geometry={nodes.Mesh009_1.geometry} material={materials.r_eye} skeleton={nodes.Mesh009_1.skeleton} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh018.geometry} material={materials.r_eye} skeleton={nodes.Mesh018.skeleton} />
        <skinnedMesh geometry={nodes.Mesh018_1.geometry} material={materials.r_eye} skeleton={nodes.Mesh018_1.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm1018_00_00_eyelid_mesh_shape.geometry} material={materials.body_a_00} skeleton={nodes.pm1018_00_00_eyelid_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_eyelid_mesh_shape_lod1.geometry} material={materials.body_a_00} skeleton={nodes.pm1018_00_00_eyelid_mesh_shape_lod1.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_eyelid_mesh_shape_lod2.geometry} material={materials.body_a_00} skeleton={nodes.pm1018_00_00_eyelid_mesh_shape_lod2.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_feeler_a_mesh_shape.geometry} material={materials.body_a_00} skeleton={nodes.pm1018_00_00_feeler_a_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_feeler_a_mesh_shape_lod1.geometry} material={materials.body_a_00} skeleton={nodes.pm1018_00_00_feeler_a_mesh_shape_lod1.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_feeler_a_mesh_shape_lod2.geometry} material={materials.body_a_00} skeleton={nodes.pm1018_00_00_feeler_a_mesh_shape_lod2.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_feeler_b_mesh_shape.geometry} material={materials.body_b_00} skeleton={nodes.pm1018_00_00_feeler_b_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_feeler_b_mesh_shape_lod1.geometry} material={materials.body_b_00} skeleton={nodes.pm1018_00_00_feeler_b_mesh_shape_lod1.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_feeler_b_mesh_shape_lod2.geometry} material={materials.body_b_00} skeleton={nodes.pm1018_00_00_feeler_b_mesh_shape_lod2.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_foot_mesh_shape.geometry} material={materials.body_b_00} skeleton={nodes.pm1018_00_00_foot_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_foot_mesh_shape_lod1.geometry} material={materials.body_b_00} skeleton={nodes.pm1018_00_00_foot_mesh_shape_lod1.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_foot_mesh_shape_lod2.geometry} material={materials.body_b_00} skeleton={nodes.pm1018_00_00_foot_mesh_shape_lod2.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_gel_mesh_shape.geometry} material={materials.body_c} skeleton={nodes.pm1018_00_00_gel_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_gel_mesh_shape_lod1.geometry} material={materials.body_c} skeleton={nodes.pm1018_00_00_gel_mesh_shape_lod1.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_gel_mesh_shape_lod2.geometry} material={materials.body_c} skeleton={nodes.pm1018_00_00_gel_mesh_shape_lod2.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_hair_mesh_shape.geometry} material={materials.body_b_00} skeleton={nodes.pm1018_00_00_hair_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_hair_mesh_shape_lod1.geometry} material={materials.body_b_00} skeleton={nodes.pm1018_00_00_hair_mesh_shape_lod1.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_hair_mesh_shape_lod2.geometry} material={materials.body_b_00} skeleton={nodes.pm1018_00_00_hair_mesh_shape_lod2.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_shoulder_mesh_shape.geometry} material={materials.body_b_00} skeleton={nodes.pm1018_00_00_shoulder_mesh_shape.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_shoulder_mesh_shape_lod1.geometry} material={materials.body_b_00} skeleton={nodes.pm1018_00_00_shoulder_mesh_shape_lod1.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      <skinnedMesh geometry={nodes.pm1018_00_00_shoulder_mesh_shape_lod2.geometry} material={materials.body_b_00} skeleton={nodes.pm1018_00_00_shoulder_mesh_shape_lod2.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/914.glb')
