/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/925.glb -o models/gltfjsx/regular/925.jsx 
Author: JojoTZ (https://sketchfab.com/JojoTZ)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/maushold-from-pokemon-scarlet-violet-c9a689709c2c499bb784012c21499262
Title: Maushold from Pokémon Scarlet & Violet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 925(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/925.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.hands_f_maus_0.geometry} material={materials.f_maus} scale={0.01} />
      <mesh geometry={nodes.hands_m_maus_0.geometry} material={materials.m_maus} scale={0.01} />
      <mesh geometry={nodes.tail_bb_maus_0.geometry} material={materials.bb_maus} scale={0.01} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/925.glb')
