/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/929.glb -o models/gltfjsx/regular/929.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 929(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/929.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_1_rootJoint} />
      <skinnedMesh geometry={nodes.Object_41.geometry} material={materials.pm1040_00_00_eye_alb} skeleton={nodes.Object_41.skeleton} />
      <skinnedMesh geometry={nodes.Object_42.geometry} material={materials.pm1040_00_00_body_b_alb} skeleton={nodes.Object_42.skeleton} />
      <skinnedMesh geometry={nodes.Object_43.geometry} material={materials.pm1040_00_00_body_a_alb} skeleton={nodes.Object_43.skeleton} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/929.glb')
