/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/942.glb -o models/gltfjsx/regular/942.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/942.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.pm1076_00_00} />
      <group position={[0, -0.144, -1.398]} rotation={[-Math.PI, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh.geometry} material={materials.body_a} skeleton={nodes.Mesh.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials.body_b} skeleton={nodes.Mesh_1.skeleton} />
      </group>
      <group position={[0, -0.144, -1.398]} rotation={[-Math.PI, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh002.geometry} material={materials.body_a} skeleton={nodes.Mesh002.skeleton} />
        <skinnedMesh geometry={nodes.Mesh002_1.geometry} material={materials.body_b} skeleton={nodes.Mesh002_1.skeleton} />
      </group>
      <group position={[0, -0.144, -1.398]} rotation={[-Math.PI, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh004.geometry} material={materials.body_a} skeleton={nodes.Mesh004.skeleton} />
        <skinnedMesh geometry={nodes.Mesh004_1.geometry} material={materials.body_b} skeleton={nodes.Mesh004_1.skeleton} />
      </group>
      <group position={[0, -0.144, -1.398]} rotation={[-Math.PI, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh001.geometry} material={materials.r_eye} skeleton={nodes.Mesh001.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_1.geometry} material={materials.r_eye} skeleton={nodes.Mesh001_1.skeleton} />
      </group>
      <group position={[0, -0.144, -1.398]} rotation={[-Math.PI, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh003.geometry} material={materials.r_eye} skeleton={nodes.Mesh003.skeleton} />
        <skinnedMesh geometry={nodes.Mesh003_1.geometry} material={materials.r_eye} skeleton={nodes.Mesh003_1.skeleton} />
      </group>
      <group position={[0, -0.144, -1.398]} rotation={[-Math.PI, 0, 0]} scale={0.025}>
        <skinnedMesh geometry={nodes.Mesh005.geometry} material={materials.r_eye} skeleton={nodes.Mesh005.skeleton} />
        <skinnedMesh geometry={nodes.Mesh005_1.geometry} material={materials.r_eye} skeleton={nodes.Mesh005_1.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/942.glb')
