/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/95.glb -o models/gltfjsx/regular/95.jsx 
Author: lucasprs51450 (https://sketchfab.com/lucasprs51450)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/onix-905c217897e14657891c32e34c58bf3f
Title: Onix
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 95(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/95.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Object_4" scale={0.01}>
          <group name="IK_Chain001" position={[-5.905, 8.575, -2.605]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material_183} skeleton={nodes.Object_7.skeleton} scale={0.01} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material_202} skeleton={nodes.Object_9.skeleton} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/95.glb')
