/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/965.glb -o models/gltfjsx/regular/965.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 965(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/965.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_8_rootJoint} />
      <skinnedMesh geometry={nodes.Object_547.geometry} material={materials.pm1046_00_00_body2_alb} skeleton={nodes.Object_547.skeleton} />
      <skinnedMesh geometry={nodes.Object_549.geometry} material={materials.pm1046_00_00_body2_alb} skeleton={nodes.Object_549.skeleton} />
      <skinnedMesh geometry={nodes.Object_550.geometry} material={materials.pm1046_00_00_body1_alb} skeleton={nodes.Object_550.skeleton} />
      <skinnedMesh geometry={nodes.Object_551.geometry} material={materials.pm1046_00_00_eye_alb} skeleton={nodes.Object_551.skeleton} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/965.glb')
