/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/967.glb -o models/gltfjsx/regular/967.jsx 
Author: Mariokart07 (https://sketchfab.com/Mariokart07)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyclizar-part-2-272302de6c0448d79b258eb4a126ef29
Title: Cyclizar Part 2
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 967(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/967.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} rotation={[-1.091, 0, 0]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.material_1} rotation={[-1.091, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.material_2} rotation={[-1.091, 0, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.material_3} rotation={[-1.091, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/967.glb')
