/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/974.glb -o models/gltfjsx/regular/974.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 974(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/974.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_12_rootJoint} />
      <skinnedMesh geometry={nodes.Object_899.geometry} material={materials['eyeball_r.004']} skeleton={nodes.Object_899.skeleton} />
      <skinnedMesh geometry={nodes.Object_900.geometry} material={materials['eyeball_l.004']} skeleton={nodes.Object_900.skeleton} />
      <skinnedMesh geometry={nodes.Object_901.geometry} material={materials.pm1051_00_00_body_alb} skeleton={nodes.Object_901.skeleton} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/regular/974.glb')
