/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/980.glb -o models/gltfjsx/regular/980.jsx 
Author: ijackprovostjr (https://sketchfab.com/ijackprovostjr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-sv-clodsire-06a8cb70d69744adb2e784639f4e111d
Title: Pokemon S&V Clodsire
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/980.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials['body_b_00.001']} skeleton={nodes.Object_7.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={1.798} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials['body_a.002']} skeleton={nodes.Object_8.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={1.798} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials['r_eye.003']} skeleton={nodes.Object_10.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={1.798} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials['r_eye.003']} skeleton={nodes.Object_11.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={1.798} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials['body_b_00.001']} skeleton={nodes.Object_13.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={1.798} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/980.glb')
