/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/984.glb -o models/gltfjsx/regular/984.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/984.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_251" geometry={nodes.Object_251.geometry} material={materials.Norm_Body_a} skeleton={nodes.Object_251.skeleton} />
        <skinnedMesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials.Norm_Body_B} skeleton={nodes.Object_252.skeleton} />
        <skinnedMesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials.Norm_Body_B} skeleton={nodes.Object_254.skeleton} />
        <skinnedMesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials['r_eye_Shiny.001']} skeleton={nodes.Object_256.skeleton} />
        <skinnedMesh name="Object_257" geometry={nodes.Object_257.geometry} material={materials['r_eye_Shiny.001']} skeleton={nodes.Object_257.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/984.glb')
