/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/985.glb -o models/gltfjsx/regular/985.jsx 
Author: ijackprovostjr (https://sketchfab.com/ijackprovostjr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-scarlet-and-violet-scream-tail-48e9026d9a204191956a604e24bd0dff
Title: Pokemon Scarlet and Violet Scream tail
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/985.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials['body_a.002']} skeleton={nodes.Object_7.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={3.575} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials['body_b.002']} skeleton={nodes.Object_9.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={3.575} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials['l_eye.002']} skeleton={nodes.Object_11.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={3.575} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials['l_eye.002']} skeleton={nodes.Object_13.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={3.575} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/985.glb')
