/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/regular/990.glb -o models/gltfjsx/regular/990.jsx 
Author: Graveyart (https://sketchfab.com/GraveyArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iron-treads-pokemon-d5e6f31fce1a47ac9f8eb8c8fd193ac5
Title: Iron Treads - Pokémon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/990.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pSphere1_blinn3_0.geometry} material={materials.blinn3} scale={0.01} />
      <mesh geometry={nodes.pSphere4_blinn2_0.geometry} material={materials.blinn2} position={[0.008, -0.008, 0.003]} rotation={[-0.089, -0.112, 0.191]} scale={0.002} />
      <mesh geometry={nodes.pCube7_blinn1_0.geometry} material={materials.blinn1} position={[0, 0.009, 0]} scale={[0.01, 0.004, 0.01]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/regular/990.glb')
