/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/alolan/19.glb -o models/gltfjsx/alolan/19.jsx 
Author: anak3d (https://sketchfab.com/anak3d1234)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/0019-rattata-alola-3d-0d0ddd2619624594841f9eaeba8077b0
Title: 0019 Rattata alola 3D
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/alolan/19.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.rattata_alola} skeleton={nodes.Object_9.skeleton} position={[0.245, -0.14, -0.338]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={4.825} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/alolan/19.glb')
