/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/alolan/38.glb -o models/gltfjsx/alolan/38.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/alolan/38.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.pm0038_61} />
      <skinnedMesh geometry={nodes.pm0038_61_BodySkin.geometry} material={materials.Body00} skeleton={nodes.pm0038_61_BodySkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.042} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.042}>
        <skinnedMesh geometry={nodes.pm0038_61_HeadSkin_2.geometry} material={materials.Eye} skeleton={nodes.pm0038_61_HeadSkin_2.skeleton} />
        <skinnedMesh geometry={nodes.pm0038_61_HeadSkin_3.geometry} material={materials.Body00} skeleton={nodes.pm0038_61_HeadSkin_3.skeleton} />
        <skinnedMesh geometry={nodes.pm0038_61_HeadSkin_4.geometry} material={materials.Body00} skeleton={nodes.pm0038_61_HeadSkin_4.skeleton} />
        <skinnedMesh geometry={nodes.pm0038_61_HeadSkin_5.geometry} material={materials.Body00} skeleton={nodes.pm0038_61_HeadSkin_5.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm0038_61_TailSkin.geometry} material={materials.Body00} skeleton={nodes.pm0038_61_TailSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.042} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/alolan/38.glb')
