/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/alolan/51.glb -o models/gltfjsx/alolan/51.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 51(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/alolan/51.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0051_00_11_ashleybody_mesh_shape_lod1_body_a.geometry} material={materials['body_a.001']} rotation={[Math.PI / 2, 0, 0]} scale={2.913} />
      <mesh geometry={nodes.pm0051_00_11_ashleyeye_mesh_shape_lod1_eye_a.geometry} material={materials['eye_a.001']} rotation={[Math.PI / 2, 0, 0]} scale={2.913} />
      <mesh geometry={nodes.pm0051_00_11_michaelhair_mesh_shape_lod1_body_b_00.geometry} material={materials['body_b_00.001']} rotation={[Math.PI / 2, 0, 0]} scale={2.913} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/alolan/51.glb')
