/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/multiForm/128-3.glb -o models/gltfjsx/multiForm/128-3.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 128-3(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/multiForm/128-3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0128_11_51_body_mesh_shape_body_a_00.geometry} material={materials.body_a_00} position={[-0.065, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0128_11_51_eye_mesh_shape_l_eye.geometry} material={materials.l_eye} position={[-0.065, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0128_11_51_fur_mesh_shape_body_b.geometry} material={materials.body_b} position={[-0.065, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/multiForm/128-3.glb')
