/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/multiform/ShayminSky.glb -o models/gltfjsx/multiform/ShayminSky.jsx 
Author: Cubone0711 (https://sketchfab.com/Cubone0711)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mobile-pokemon-home-492-shaymin-sky-forme-125396aaa82441d49ca35da861b4e456
Title: Mobile - Pokemon HOME - 492 Shaymin Sky Forme
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/multiForm/ShayminSky.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.pm0492_12_00_BodyVco00} skeleton={nodes.Object_6.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.pm0492_12_00_BodyVco00} skeleton={nodes.Object_7.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.pm0492_12_00_REye} skeleton={nodes.Object_8.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.pm0492_12_00_Mouth} skeleton={nodes.Object_9.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.pm0492_12_00_BodyVco00} skeleton={nodes.Object_10.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.pm0492_12_00_BodyVco00} skeleton={nodes.Object_11.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.pm0492_12_00_BodyVco00} skeleton={nodes.Object_12.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.pm0492_12_00_REye} skeleton={nodes.Object_13.skeleton} scale={0.025} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/multiForm/ShayminSky.glb')
