/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/hisuian/549.glb -o models/gltfjsx/hisuian/549.jsx 
Author: Redpikmin_1234 (https://sketchfab.com/Redpikmin_1234)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hisuian-form-lilligant-b67d5e62e4cc463e8071ef156ba70b3b
Title: Hisuian Form Lilligant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 549(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/hisuian/549.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.body_00} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.l_eye} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/hisuian/549.glb')
