/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/hisuian/724.glb -o models/gltfjsx/hisuian/724.jsx 
Author: LunaEagle (https://sketchfab.com/LunaEagle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/decidueye-hisuian-694aef0a67bf4c53bb739f4cea95811c
Title: Decidueye Hisuian
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 724(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/hisuian/724.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_305" geometry={nodes.Object_305.geometry} material={materials['pm0724_00_41-BodyB']} skeleton={nodes.Object_305.skeleton} scale={0.5} />
        <skinnedMesh name="Object_307" geometry={nodes.Object_307.geometry} material={materials['pm0724_00_41-BodyA']} skeleton={nodes.Object_307.skeleton} scale={0.5} />
        <skinnedMesh name="Object_309" geometry={nodes.Object_309.geometry} material={materials['pm0724_00_41-BodyB']} skeleton={nodes.Object_309.skeleton} scale={0.5} />
        <skinnedMesh name="Object_311" geometry={nodes.Object_311.geometry} material={materials['pm0724_00_41-BodyB']} skeleton={nodes.Object_311.skeleton} scale={0.5} />
        <skinnedMesh name="Object_313" geometry={nodes.Object_313.geometry} material={materials['pm0724_00_41-BodyA']} skeleton={nodes.Object_313.skeleton} scale={0.5} />
        <skinnedMesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials['pm0724_00_41-LEye']} skeleton={nodes.Object_314.skeleton} scale={0.5} />
        <skinnedMesh name="Object_315" geometry={nodes.Object_315.geometry} material={materials['pm0724_00_41-LEye']} skeleton={nodes.Object_315.skeleton} scale={0.5} />
        <skinnedMesh name="Object_317" geometry={nodes.Object_317.geometry} material={materials['pm0724_00_41-BodyB']} skeleton={nodes.Object_317.skeleton} scale={0.5} />
        <skinnedMesh name="Object_319" geometry={nodes.Object_319.geometry} material={materials['pm0724_00_41-BodyB']} skeleton={nodes.Object_319.skeleton} scale={0.5} />
        <skinnedMesh name="Object_321" geometry={nodes.Object_321.geometry} material={materials['pm0724_00_41-BodyA']} skeleton={nodes.Object_321.skeleton} scale={0.5} />
        <skinnedMesh name="Object_323" geometry={nodes.Object_323.geometry} material={materials['pm0724_00_41-BodyB']} skeleton={nodes.Object_323.skeleton} scale={0.5} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/hisuian/724.glb')
