/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/galar/109.glb -o models/gltfjsx/galar/109.jsx 
Author: reactorous (https://sketchfab.com/reactorous)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/galarian-koffing-71592d32abce45a89abb6e8682a7b893
Title: Galarian Koffing
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/galar/109.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box001_Group16296_0.geometry} material={materials.Group16296} position={[2090.335, -4886.19, 5504.316]} scale={229.971} />
      <mesh geometry={nodes.Group16296_Box001_0.geometry} material={materials.Box001} position={[2090.335, -4886.19, 5504.316]} scale={229.971} />
      <mesh geometry={nodes.Group20204_Body_Mat_0.geometry} material={materials.Body_Mat} position={[2090.335, -4886.19, 5504.316]} scale={229.971} />
      <mesh geometry={nodes.Group48858_Grey_Plastic_0.geometry} material={materials.Grey_Plastic} position={[2090.335, -4976.795, 6322.68]} scale={229.971} />
      <mesh geometry={nodes.Group48861_Group48861_0.geometry} material={materials.Group48861} position={[2090.335, -4886.19, 5504.316]} scale={229.971} />
      <instancedMesh args={[nodes.Sphere001_Box001_0.geometry, materials.Box001, 11]} instanceMatrix={nodes.Sphere001_Box001_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/galar/109.glb')
