/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/galar/144.glb -o models/gltfjsx/galar/144.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 144(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/galar/144.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0144_00_31_body_mesh_shape_body_a_00.geometry} material={materials.body_a_00} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0144_00_31_body_mesh_shape_body_b.geometry} material={materials.body_b} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0144_00_31_eye_mesh_shape_l_eye.geometry} material={materials.l_eye} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/galar/144.glb')
