/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/galar/146.glb -o models/gltfjsx/galar/146.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/galar/146.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0146_00_31_body_mesh_shape_lod1_body_a.geometry} material={materials['body_a.005']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0146_00_31_body_mesh_shape_lod1_body_b.geometry} material={materials['body_b.005']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0146_00_31_eye_mesh_shape_lod1_l_eye.geometry} material={materials['l_eye.005']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0146_00_31_fire_a_01_mesh_shape_lod1_fire_a_00.geometry} material={materials['fire_a_00.005']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0146_00_31_fire_a_02_mesh_shape_lod1_fire_a_01.geometry} material={materials['fire_a_01.005']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0146_00_31_fire_b_mesh_shape_lod1_fire_b.geometry} material={materials['fire_b.005']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/galar/146.glb')
