/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/galar/80.glb -o models/gltfjsx/galar/80.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 80(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/galar/80.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0080_00_31_body_a_mesh_shape_lod1_body_a_00.geometry} material={materials.body_a_00} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0080_00_31_body_b_mesh_shape_lod1_body_b_00.geometry} material={materials.body_b_00} position={[0.417, 1.324, 0.536]} rotation={[Math.PI / 2, 0, 2.659]} />
      <mesh geometry={nodes.pm0080_00_31_body_b_mesh_shape_lod1_l_eye_b.geometry} material={materials.l_eye_b} position={[0.417, 1.324, 0.536]} rotation={[Math.PI / 2, 0, 2.659]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/galar/80.glb')
