/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/opt/gmax/12.glb -o models/gltfjsx/gmax/12.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/gmax/12.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.pm0012_81_00} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <skinnedMesh geometry={nodes.pm0012_81_00_BodySkin_2.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_BodySkin_2.skeleton} />
        <skinnedMesh geometry={nodes.pm0012_81_00_BodySkin_3.geometry} material={materials.Eye} skeleton={nodes.pm0012_81_00_BodySkin_3.skeleton} />
        <skinnedMesh geometry={nodes.pm0012_81_00_BodySkin_4.geometry} material={materials.BodyA01} skeleton={nodes.pm0012_81_00_BodySkin_4.skeleton} />
        <skinnedMesh geometry={nodes.pm0012_81_00_BodySkin_5.geometry} material={materials.BodyA01} skeleton={nodes.pm0012_81_00_BodySkin_5.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.pm0012_81_00_FurSkin.geometry} material={materials.BodyA01} skeleton={nodes.pm0012_81_00_FurSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesASkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesASkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesBSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesBSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesCSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesCSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesDSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesDSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesESkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesESkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesFSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesFSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesGSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesGSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesHSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesHSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesISkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesISkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesJSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesJSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesKSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesKSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesLSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesLSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesMSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesMSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesNSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesNSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesOSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesOSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesPSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesPSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesQSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesQSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesRSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesRSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesSSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesSSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesTSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesTSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesUSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesUSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesVSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesVSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesWSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesWSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesXSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesXSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_ScalesYSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_ScalesYSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_WingA1LSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_WingA1LSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_WingA1RSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_WingA1RSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_WingA2LSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_WingA2LSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_WingA2RSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_WingA2RSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_WingB1LSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_WingB1LSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_WingB1RSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_WingB1RSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_WingB2LSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_WingB2LSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.pm0012_81_00_WingB2RSkin.geometry} material={materials.BodyC02IncNon} skeleton={nodes.pm0012_81_00_WingB2RSkin.skeleton} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D-api/main/models/opt/gmax/12.glb')
